/*  Java code generated by apiwrapper for GAMS Version 30.1.0
 *
 * GAMS - Loading mechanism for GAMS Expert-Level APIs
 *
 * Copyright (c) 2016-2020 GAMS Software GmbH <support@gams.com>
 * Copyright (c) 2016-2020 GAMS Development Corp. <support@gams.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.gams.api;

import java.io.File;

public class gamsx {
   private long gamsxPtr = 0;
   public native static int      GetReady (String[] msg);
   public native static int      GetReadyD(String dirName, String[] msg);
   public native static int      GetReadyL(String libName, String[] msg);
   public native int      Create   (String[] msg);
   public native int      CreateD  (String dirName, String[] msg);
   public native int      CreateL  (String libName, String[] msg);
   public native int      Free     ();
   public native int      RunExecDLL(long optPtr, String sysDir, int AVerbose, String []Msg);
   public native boolean      ShowError(String fNameLog, String []errorLine, String []errorTyp, String []gmsLine);
   public native void      AddBreakPoint(String fn, int lineNr);
   public native void      ClearBreakPoints();
   public native int      SystemInfo(int []NrSy, int []NrUel);
   public native int      SymbolInfo(int SyNr, String []SyName, String []SyExplTxt, int []SyDim, int []SyTyp, int []SyCount, int []SyUserInfo);
   public native int      FindSymbol(String SyName);
   public native int      DataReadRawStart(int SyNr, int []SyCount);
   public native int      DataReadRaw(int []Elements, double []Vals, int []FDim);
   public native int      DataReadDone();
   public native int      DataWriteRawStart(int SyNr, boolean DoMerge);
   public native int      DataWriteRaw(int []Elements, double []Vals);
   public native int      DataWriteDone();
   public native void      RegisterCB1(String CB1, long userMem);
   public native void      RegisterCB2(String CB2, long userMem1, long userMem2);
   public native String      GetCB1();
   public native String      GetCB2();
   public native long      GetCB1UM();
   public native long      GetCB2UM1();
   public native long      GetCB2UM2();
   public native void      SWSet(int x);
   public native boolean      StepThrough();
   public native void      StepThroughSet(boolean x);
   public native boolean      RunToEnd();
   public native void      RunToEndSet(boolean x);
   public native boolean      CB1Defined();
   public native boolean      CB2Defined();
   private native String      UelName(int uel, String []sst_result);
   public String      UelName(int uel) {
       String[] sst_result = new String[1];
       return      UelName(uel, sst_result);
   }
   public        long      GetgamsxPtr(){ return gamsxPtr;}
   public gamsx () { }
   public gamsx (long gamsxPtr) {
      this.gamsxPtr = gamsxPtr;
   }
   static {
      String stem = "gamsxjni";
      String bitsuffix = "";
 
      if ( System.getProperty("os.arch").toLowerCase().indexOf("64") >= 0 ||
           System.getProperty("os.arch").toLowerCase().indexOf("sparcv9") >= 0 ) {
           bitsuffix = "64";
      }
 
      String os = System.getProperty("os.name").toLowerCase();
      String prefix = "";
      String suffix = "";
 
      if (os.indexOf("win") >=0) {
         suffix = ".dll";
      } else if (os.indexOf("mac") >= 0) {
          prefix = "lib";
          suffix = ".dylib";
      } else {
          prefix = "lib";
          suffix = ".so";
      }
 
      boolean loaded = false;
      try  {
           String libPath = System.getProperty("java.library.path");
           if (libPath != null) {
               for (String str : libPath.split(System.getProperty("path.separator")) ) {
                   File curPath = new File(str);
                   String fileName = curPath.getCanonicalPath() + File.separator + prefix + stem + bitsuffix + suffix;
                   if ( new File(fileName).exists() ) {
                       System.load(fileName);
                       loaded = true;
                       break;
                   }
                }
            }
       } catch (Exception e) {
           loaded = false;
       } catch (UnsatisfiedLinkError e1) {
           loaded = false;
       } finally {
            if (!loaded) {
                try  {
                   System.loadLibrary(stem + bitsuffix);
                } catch (UnsatisfiedLinkError e1) {
                    String libraryFullPath = null;
                    String classPath = null;
                    try {
                       String packageName = (Class.forName(gamsx.class.getName()).getPackage().getName());
                       StringBuilder sb = new StringBuilder();
                       String[] bs = packageName.split("\\.");
                       for (String s : bs) {
                          sb.append(s);
                          sb.append("/");
                        }
                       sb.append(gamsx.class.getSimpleName());
                       sb.append(".class");
                       ClassLoader cl = gamsx.class.getClassLoader();
 
                       classPath = cl.getResource(sb.toString()).getPath();
                       sb.insert(0, "/");
                       classPath = classPath.substring(0, classPath.lastIndexOf(sb.toString()));
                       if (classPath.endsWith("!")) {
                          int index = classPath.lastIndexOf("/");
                          if (index >= 0)
                              classPath = classPath.substring(0, index);
                        }
                       if (classPath.indexOf("/") >= 0) {
                           classPath = classPath.substring(classPath.indexOf(":")+1,classPath.length());
                       }
 
                       libraryFullPath = classPath + "/" + prefix + stem + bitsuffix + suffix ;
                       java.io.File apath = new java.io.File(libraryFullPath);
                       libraryFullPath = java.net.URLDecoder.decode(apath.getAbsolutePath(), "UTF-8");
                    } catch (Exception e2) {
                          e2.printStackTrace();
                          e1.printStackTrace();
                          throw (e1);
                    } finally {
                         if (libraryFullPath == null)  {
                            e1.printStackTrace();
                            throw (e1);
                         }
                    }
 
                    try {
                        System.load(libraryFullPath);
                    } catch (UnsatisfiedLinkError e3) {
                        e3.printStackTrace();
                        throw (e3);
                    }
               }
           }
        }
     }
}
