/*  Java code generated by apiwrapper for GAMS Version 30.1.0
 *
 * GAMS - Loading mechanism for GAMS Expert-Level APIs
 *
 * Copyright (c) 2016-2020 GAMS Software GmbH <support@gams.com>
 * Copyright (c) 2016-2020 GAMS Development Corp. <support@gams.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.gams.api;

import java.io.File;

public class gdx {
   private long gdxPtr = 0;
   public native static int    GetReady (String[] msg);
   public native static int    GetReadyD(String dirName, String[] msg);
   public native static int    GetReadyL(String libName, String[] msg);
   public native int    Create   (String[] msg);
   public native int    CreateD  (String dirName, String[] msg);
   public native int    CreateL  (String libName, String[] msg);
   public native int    Free     ();
   public native int    AcronymAdd(String AName, String Txt, int AIndx);
   public native int    AcronymCount();
   public native int    AcronymGetInfo(int N, String []AName, String []Txt, int []AIndx);
   public native int    AcronymGetMapping(int N, int []orgIndx, int []newIndx, int []autoIndex);
   public native int    AcronymIndex(double V);
   public native int    AcronymName(double V, String []AName);
   public native int    AcronymNextNr(int NV);
   public native int    AcronymSetInfo(int N, String AName, String Txt, int AIndx);
   public native double    AcronymValue(int AIndx);
   public native int    AddAlias(String Id1, String Id2);
   public native int    AddSetText(String Txt, int []TxtNr);
   public native int    AutoConvert(int NV);
   public native int    Close();
   public native int    DataErrorCount();
   public native int    DataErrorRecord(int RecNr, int []KeyInt, double []Values);
   public native int    DataErrorRecordX(int RecNr, int []KeyInt, double []Values);
   public native int    DataReadDone();
   public native int    DataReadFilteredStart(int SyNr, int []FilterAction, int []NrRecs);
   public native int    DataReadMap(int RecNr, int []KeyInt, double []Values, int []DimFrst);
   public native int    DataReadMapStart(int SyNr, int []NrRecs);
   public native int    DataReadRaw(int []KeyInt, double []Values, int []DimFrst);
   public native int    DataReadRawFast(int SyNr, String DP, int []NrRecs);
   public native int    DataReadRawFastFilt(int SyNr, String []UelFilterStr, String DP);
   public native int    DataReadRawStart(int SyNr, int []NrRecs);
   public native int    DataReadSlice(String []UelFilterStr, int []Dimen, String DP);
   public native int    DataReadSliceStart(int SyNr, int []ElemCounts);
   public native int    DataReadStr(String []KeyStr, double []Values, int []DimFrst);
   public native int    DataReadStrStart(int SyNr, int []NrRecs);
   public native int    DataSliceUELS(int []SliceKeyInt, String []KeyStr);
   public native int    DataWriteDone();
   public native int    DataWriteMap(int []KeyInt, double []Values);
   public native int    DataWriteMapStart(String SyId, String ExplTxt, int Dimen, int Typ, int UserInfo);
   public native int    DataWriteRaw(int []KeyInt, double []Values);
   public native int    DataWriteRawStart(String SyId, String ExplTxt, int Dimen, int Typ, int UserInfo);
   public native int    DataWriteStr(String []KeyStr, double []Values);
   public native int    DataWriteStrStart(String SyId, String ExplTxt, int Dimen, int Typ, int UserInfo);
   public native int    GetDLLVersion(String []V);
   public native int    ErrorCount();
   public native int    ErrorStr(int ErrNr, String []ErrMsg);
   public native int    FileInfo(int []FileVer, int []ComprLev);
   public native int    FileVersion(String []FileStr, String []ProduceStr);
   public native int    FilterExists(int FilterNr);
   public native int    FilterRegister(int UelMap);
   public native int    FilterRegisterDone();
   public native int    FilterRegisterStart(int FilterNr);
   public native int    FindSymbol(String SyId, int []SyNr);
   public native int    GetElemText(int TxtNr, String []Txt, int []Node);
   public native int    GetLastError();
   public native long    GetMemoryUsed();
   public native int    GetSpecialValues(double []AVals);
   public native int    GetUEL(int UelNr, String []Uel);
   public native int    MapValue(double D, int []sv);
   public native int    OpenAppend(String FileName, String Producer, int []ErrNr);
   public native int    OpenRead(String FileName, int []ErrNr);
   public native int    OpenReadEx(String FileName, int ReadMode, int []ErrNr);
   public native int    OpenWrite(String FileName, String Producer, int []ErrNr);
   public native int    OpenWriteEx(String FileName, String Producer, int Compr, int []ErrNr);
   public native int    ResetSpecialValues();
   public native int    SetHasText(int SyNr);
   public native int    SetReadSpecialValues(double []AVals);
   public native int    SetSpecialValues(double []AVals);
   public native int    SetTextNodeNr(int TxtNr, int Node);
   public native int    SetTraceLevel(int N, String s);
   public native int    SymbIndxMaxLength(int SyNr, int []LengthInfo);
   public native int    SymbMaxLength();
   public native int    SymbolAddComment(int SyNr, String Txt);
   public native int    SymbolGetComment(int SyNr, int N, String []Txt);
   public native int    SymbolGetDomain(int SyNr, int []DomainSyNrs);
   public native int    SymbolGetDomainX(int SyNr, String []DomainIDs);
   public native int    SymbolDim(int SyNr);
   public native int    SymbolInfo(int SyNr, String []SyId, int []Dimen, int []Typ);
   public native int    SymbolInfoX(int SyNr, int []RecCnt, int []UserInfo, String []ExplTxt);
   public native int    SymbolSetDomain(String []DomainIDs);
   public native int    SymbolSetDomainX(int SyNr, String []DomainIDs);
   public native int    SystemInfo(int []SyCnt, int []UelCnt);
   public native int    UELMaxLength();
   public native int    UELRegisterDone();
   public native int    UELRegisterMap(int UMap, String Uel);
   public native int    UELRegisterMapStart();
   public native int    UELRegisterRaw(String Uel);
   public native int    UELRegisterRawStart();
   public native int    UELRegisterStr(String Uel, int []UelNr);
   public native int    UELRegisterStrStart();
   public native int    UMFindUEL(String Uel, int []UelNr, int []UelMap);
   public native int    UMUelGet(int UelNr, String []Uel, int []UelMap);
   public native int    UMUelInfo(int []UelCnt, int []HighMap);
   public native int    GetDomainElements(int SyNr, int DimPos, int FilterNr, String DP, int []NrElem, long Uptr);
   public native int    CurrentDim();
   public native int    RenameUEL(String OldName, String NewName);
   public        long    GetgdxPtr(){ return gdxPtr;}
   public gdx () { }
   public gdx (long gdxPtr) {
      this.gdxPtr = gdxPtr;
   }
   static {
      String stem = "gdxjni";
      String bitsuffix = "";
 
      if ( System.getProperty("os.arch").toLowerCase().indexOf("64") >= 0 ||
           System.getProperty("os.arch").toLowerCase().indexOf("sparcv9") >= 0 ) {
           bitsuffix = "64";
      }
 
      String os = System.getProperty("os.name").toLowerCase();
      String prefix = "";
      String suffix = "";
 
      if (os.indexOf("win") >=0) {
         suffix = ".dll";
      } else if (os.indexOf("mac") >= 0) {
          prefix = "lib";
          suffix = ".dylib";
      } else {
          prefix = "lib";
          suffix = ".so";
      }
 
      boolean loaded = false;
      try  {
           String libPath = System.getProperty("java.library.path");
           if (libPath != null) {
               for (String str : libPath.split(System.getProperty("path.separator")) ) {
                   File curPath = new File(str);
                   String fileName = curPath.getCanonicalPath() + File.separator + prefix + stem + bitsuffix + suffix;
                   if ( new File(fileName).exists() ) {
                       System.load(fileName);
                       loaded = true;
                       break;
                   }
                }
            }
       } catch (Exception e) {
           loaded = false;
       } catch (UnsatisfiedLinkError e1) {
           loaded = false;
       } finally {
            if (!loaded) {
                try  {
                   System.loadLibrary(stem + bitsuffix);
                } catch (UnsatisfiedLinkError e1) {
                    String libraryFullPath = null;
                    String classPath = null;
                    try {
                       String packageName = (Class.forName(gdx.class.getName()).getPackage().getName());
                       StringBuilder sb = new StringBuilder();
                       String[] bs = packageName.split("\\.");
                       for (String s : bs) {
                          sb.append(s);
                          sb.append("/");
                        }
                       sb.append(gdx.class.getSimpleName());
                       sb.append(".class");
                       ClassLoader cl = gdx.class.getClassLoader();
 
                       classPath = cl.getResource(sb.toString()).getPath();
                       sb.insert(0, "/");
                       classPath = classPath.substring(0, classPath.lastIndexOf(sb.toString()));
                       if (classPath.endsWith("!")) {
                          int index = classPath.lastIndexOf("/");
                          if (index >= 0)
                              classPath = classPath.substring(0, index);
                        }
                       if (classPath.indexOf("/") >= 0) {
                           classPath = classPath.substring(classPath.indexOf(":")+1,classPath.length());
                       }
 
                       libraryFullPath = classPath + "/" + prefix + stem + bitsuffix + suffix ;
                       java.io.File apath = new java.io.File(libraryFullPath);
                       libraryFullPath = java.net.URLDecoder.decode(apath.getAbsolutePath(), "UTF-8");
                    } catch (Exception e2) {
                          e2.printStackTrace();
                          e1.printStackTrace();
                          throw (e1);
                    } finally {
                         if (libraryFullPath == null)  {
                            e1.printStackTrace();
                            throw (e1);
                         }
                    }
 
                    try {
                        System.load(libraryFullPath);
                    } catch (UnsatisfiedLinkError e3) {
                        e3.printStackTrace();
                        throw (e3);
                    }
               }
           }
        }
     }
}
