/*  Java Native Interrface code generated by apiwrapper for GAMS Version 30.1.0
 *
 * GAMS - Loading mechanism for GAMS Expert-Level APIs
 *
 * Copyright (c) 2016-2020 GAMS Software GmbH <support@gams.com>
 * Copyright (c) 2016-2020 GAMS Development Corp. <support@gams.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* #include <locale.h> */
#include <gdxcc.h>

/* at least for some JNI implementations, JNIEXPORT is not setup to
 * explicitly set visibility to default when using GNU compilers;
 * thus, we do this globally for all functions via this pragma
 *  (which is nicer than redefining JNIEXPORT)
 */
#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif

typedef union foo { void *p; jlong i; } u64_t;

typedef char string255[256];
typedef char stringUEL[GLOBAL_UEL_IDENT_SIZE];

static char* sig_gdxDataReadRawFast_DP = NULL;
static char* sig_gdxDataReadRawFastFilt_DP = NULL;
static char* sig_gdxDataReadSlice_DP = NULL;
static char* sig_gdxGetDomainElements_DP = NULL;
static char* methodname_gdxDataReadRawFast_DP = NULL;
static char* methodname_gdxDataReadRawFastFilt_DP = NULL;
static char* methodname_gdxDataReadSlice_DP = NULL;
static char* methodname_gdxGetDomainElements_DP = NULL;
static char* classname_gdxDataReadRawFast_DP = NULL;
static char* classname_gdxDataReadRawFastFilt_DP = NULL;
static char* classname_gdxDataReadSlice_DP = NULL;
static char* classname_gdxGetDomainElements_DP = NULL;
static jintArray gdxDataReadRawFast_Indx = NULL;
static jdoubleArray gdxDataReadRawFast_Vals = NULL;
static jintArray gdxDataReadRawFastFilt_Indx = NULL;
static jdoubleArray gdxDataReadRawFastFilt_Vals = NULL;
static jintArray gdxDataReadSlice_Indx = NULL;
static jdoubleArray gdxDataReadSlice_Vals = NULL;
static char  ClassDotMethodName[512];
static int   ReturnName = 0;

static void printerr(const char *mess, const char*name)
{
   fprintf(stderr,"%s: %s\n",mess,name);
   exit(1);
}

static char* getMethodName_(const char* name)
{
    char *s;
    s = strrchr(name,'.');
    if (s==NULL)
        return NULL;
    ++s;
    return strdup(s);
}

static char* getClassName_(const char* name)
{
    char *s;
    char *t;
    t = strdup(name);
    s = strrchr(t,'.');
    if (s==NULL)
        return NULL;
    *s = '\0';
    return t;
}

static JavaVM *Cached_JVM = NULL;
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved)
{
    Cached_JVM = vm;
    gdxInitMutexes();
    return JNI_VERSION_1_2;
}

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM *vm, void *reserved)
{
    gdxFiniMutexes();
}

/* Prototypes */
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetReady(JNIEnv *env, jobject obj, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetReadyD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetReadyL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_Create(JNIEnv *env, jobject obj, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_CreateD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_CreateL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_Free(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymAdd(JNIEnv *env, jobject obj, jstring AName, jstring Txt, jint AIndx);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymCount(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymGetInfo(JNIEnv *env, jobject obj, jint N, jobjectArray AName, jobjectArray Txt, jintArray AIndx);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymGetMapping(JNIEnv *env, jobject obj, jint N, jintArray orgIndx, jintArray newIndx, jintArray autoIndex);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymIndex(JNIEnv *env, jobject obj, jdouble V);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymName(JNIEnv *env, jobject obj, jdouble V, jobjectArray AName);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymNextNr(JNIEnv *env, jobject obj, jint NV);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymSetInfo(JNIEnv *env, jobject obj, jint N, jstring AName, jstring Txt, jint AIndx);
JNIEXPORT jdouble JNICALL Java_com_gams_api_gdx_AcronymValue(JNIEnv *env, jobject obj, jint AIndx);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AddAlias(JNIEnv *env, jobject obj, jstring Id1, jstring Id2);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AddSetText(JNIEnv *env, jobject obj, jstring Txt, jintArray TxtNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AutoConvert(JNIEnv *env, jobject obj, jint NV);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_Close(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataErrorCount(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataErrorRecord(JNIEnv *env, jobject obj, jint RecNr, jintArray KeyInt, jdoubleArray Values);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataErrorRecordX(JNIEnv *env, jobject obj, jint RecNr, jintArray KeyInt, jdoubleArray Values);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadDone(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadFilteredStart(JNIEnv *env, jobject obj, jint SyNr, jintArray FilterAction, jintArray NrRecs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadMap(JNIEnv *env, jobject obj, jint RecNr, jintArray KeyInt, jdoubleArray Values, jintArray DimFrst);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadMapStart(JNIEnv *env, jobject obj, jint SyNr, jintArray NrRecs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRaw(JNIEnv *env, jobject obj, jintArray KeyInt, jdoubleArray Values, jintArray DimFrst);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRawFast(JNIEnv *env, jobject obj, jint SyNr, jstring DP, jintArray NrRecs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRawFastFilt(JNIEnv *env, jobject obj, jint SyNr, jobjectArray UelFilterStr, jstring DP);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRawStart(JNIEnv *env, jobject obj, jint SyNr, jintArray NrRecs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadSlice(JNIEnv *env, jobject obj, jobjectArray UelFilterStr, jintArray Dimen, jstring DP);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadSliceStart(JNIEnv *env, jobject obj, jint SyNr, jintArray ElemCounts);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadStr(JNIEnv *env, jobject obj, jobjectArray KeyStr, jdoubleArray Values, jintArray DimFrst);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadStrStart(JNIEnv *env, jobject obj, jint SyNr, jintArray NrRecs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataSliceUELS(JNIEnv *env, jobject obj, jintArray SliceKeyInt, jobjectArray KeyStr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteDone(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteMap(JNIEnv *env, jobject obj, jintArray KeyInt, jdoubleArray Values);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteMapStart(JNIEnv *env, jobject obj, jstring SyId, jstring ExplTxt, jint Dimen, jint Typ, jint UserInfo);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteRaw(JNIEnv *env, jobject obj, jintArray KeyInt, jdoubleArray Values);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteRawStart(JNIEnv *env, jobject obj, jstring SyId, jstring ExplTxt, jint Dimen, jint Typ, jint UserInfo);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteStr(JNIEnv *env, jobject obj, jobjectArray KeyStr, jdoubleArray Values);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteStrStart(JNIEnv *env, jobject obj, jstring SyId, jstring ExplTxt, jint Dimen, jint Typ, jint UserInfo);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetDLLVersion(JNIEnv *env, jobject obj, jobjectArray V);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_ErrorCount(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_ErrorStr(JNIEnv *env, jobject obj, jint ErrNr, jobjectArray ErrMsg);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FileInfo(JNIEnv *env, jobject obj, jintArray FileVer, jintArray ComprLev);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FileVersion(JNIEnv *env, jobject obj, jobjectArray FileStr, jobjectArray ProduceStr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterExists(JNIEnv *env, jobject obj, jint FilterNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterRegister(JNIEnv *env, jobject obj, jint UelMap);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterRegisterDone(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterRegisterStart(JNIEnv *env, jobject obj, jint FilterNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FindSymbol(JNIEnv *env, jobject obj, jstring SyId, jintArray SyNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetElemText(JNIEnv *env, jobject obj, jint TxtNr, jobjectArray Txt, jintArray Node);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetLastError(JNIEnv *env, jobject obj);
JNIEXPORT jlong JNICALL Java_com_gams_api_gdx_GetMemoryUsed(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetSpecialValues(JNIEnv *env, jobject obj, jdoubleArray AVals);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetUEL(JNIEnv *env, jobject obj, jint UelNr, jobjectArray Uel);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_MapValue(JNIEnv *env, jobject obj, jdouble D, jintArray sv);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenAppend(JNIEnv *env, jobject obj, jstring FileName, jstring Producer, jintArray ErrNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenRead(JNIEnv *env, jobject obj, jstring FileName, jintArray ErrNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenReadEx(JNIEnv *env, jobject obj, jstring FileName, jint ReadMode, jintArray ErrNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenWrite(JNIEnv *env, jobject obj, jstring FileName, jstring Producer, jintArray ErrNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenWriteEx(JNIEnv *env, jobject obj, jstring FileName, jstring Producer, jint Compr, jintArray ErrNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_ResetSpecialValues(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetHasText(JNIEnv *env, jobject obj, jint SyNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetReadSpecialValues(JNIEnv *env, jobject obj, jdoubleArray AVals);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetSpecialValues(JNIEnv *env, jobject obj, jdoubleArray AVals);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetTextNodeNr(JNIEnv *env, jobject obj, jint TxtNr, jint Node);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetTraceLevel(JNIEnv *env, jobject obj, jint N, jstring s);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbIndxMaxLength(JNIEnv *env, jobject obj, jint SyNr, jintArray LengthInfo);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbMaxLength(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolAddComment(JNIEnv *env, jobject obj, jint SyNr, jstring Txt);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolGetComment(JNIEnv *env, jobject obj, jint SyNr, jint N, jobjectArray Txt);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolGetDomain(JNIEnv *env, jobject obj, jint SyNr, jintArray DomainSyNrs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolGetDomainX(JNIEnv *env, jobject obj, jint SyNr, jobjectArray DomainIDs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolDim(JNIEnv *env, jobject obj, jint SyNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolInfo(JNIEnv *env, jobject obj, jint SyNr, jobjectArray SyId, jintArray Dimen, jintArray Typ);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolInfoX(JNIEnv *env, jobject obj, jint SyNr, jintArray RecCnt, jintArray UserInfo, jobjectArray ExplTxt);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolSetDomain(JNIEnv *env, jobject obj, jobjectArray DomainIDs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolSetDomainX(JNIEnv *env, jobject obj, jint SyNr, jobjectArray DomainIDs);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SystemInfo(JNIEnv *env, jobject obj, jintArray SyCnt, jintArray UelCnt);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELMaxLength(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterDone(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterMap(JNIEnv *env, jobject obj, jint UMap, jstring Uel);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterMapStart(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterRaw(JNIEnv *env, jobject obj, jstring Uel);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterRawStart(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterStr(JNIEnv *env, jobject obj, jstring Uel, jintArray UelNr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterStrStart(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UMFindUEL(JNIEnv *env, jobject obj, jstring Uel, jintArray UelNr, jintArray UelMap);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UMUelGet(JNIEnv *env, jobject obj, jint UelNr, jobjectArray Uel, jintArray UelMap);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UMUelInfo(JNIEnv *env, jobject obj, jintArray UelCnt, jintArray HighMap);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetDomainElements(JNIEnv *env, jobject obj, jint SyNr, jint DimPos, jint FilterNr, jstring DP, jintArray NrElem, jlong Uptr);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_CurrentDim(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gdx_RenameUEL(JNIEnv *env, jobject obj, jstring OldName, jstring NewName);

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetReady(JNIEnv *env, jobject obj, jobjectArray msg)
{
   int rc_GetReady;
   jstring local_msg;
   char buffer_msg[256];
   rc_GetReady = gdxGetReady(buffer_msg, sizeof(buffer_msg));
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReady;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetReadyD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg)
{
   int rc_GetReadyD;
   char *local_dirName;
   jstring local_msg;
   char buffer_msg[256];
   buffer_msg[0] = '\0';
   local_dirName = (char *) (*env)->GetStringUTFChars(env, dirName, NULL);
   rc_GetReadyD = gdxGetReadyD(local_dirName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, dirName, local_dirName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReadyD;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetReadyL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg)
{
   int rc_GetReadyL;
   char *local_libName;
   jstring local_msg;
   char buffer_msg[256];
   buffer_msg[0] = '\0';
   local_libName = (char *) (*env)->GetStringUTFChars(env, libName, NULL);
   rc_GetReadyL = gdxGetReadyL(local_libName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, libName, local_libName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReadyL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_Create(JNIEnv *env, jobject obj, jobjectArray msg)
{
   int rc_Create;
   jfieldID fid;
   u64_t pgdx;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_Create = gdxCreate((gdxHandle_t *)&pgdx.p, buffer_msg, sizeof(buffer_msg));
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, pgdx.i);
   return rc_Create;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_CreateD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg)
{
   int rc_CreateD;
   jfieldID fid;
   u64_t pgdx;
   char *local_dirName;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_dirName = (char *) (*env)->GetStringUTFChars(env, dirName, NULL);
   rc_CreateD = gdxCreateD((gdxHandle_t *)&pgdx.p, local_dirName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, dirName, local_dirName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, pgdx.i);
   return rc_CreateD;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_CreateL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg)
{
   int rc_CreateL;
   jfieldID fid;
   u64_t pgdx;
   char *local_libName;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_libName = (char *) (*env)->GetStringUTFChars(env, libName, NULL);
   rc_CreateL = gdxCreateL((gdxHandle_t *)&pgdx.p, local_libName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, libName, local_libName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, pgdx.i);
   return rc_CreateL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_Free(JNIEnv *env, jobject obj)
{
   int rc_Free;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_Free = gdxFree((gdxHandle_t *)&pgdx.p);
   (*env)->SetLongField(env, obj, fid, pgdx.i);
   (*env)->DeleteGlobalRef(env, gdxDataReadRawFast_Indx); gdxDataReadRawFast_Indx = NULL;
   (*env)->DeleteGlobalRef(env, gdxDataReadRawFast_Vals); gdxDataReadRawFast_Vals = NULL;
   (*env)->DeleteGlobalRef(env, gdxDataReadRawFastFilt_Indx); gdxDataReadRawFastFilt_Indx = NULL;
   (*env)->DeleteGlobalRef(env, gdxDataReadRawFastFilt_Vals); gdxDataReadRawFastFilt_Vals = NULL;
   (*env)->DeleteGlobalRef(env, gdxDataReadSlice_Indx); gdxDataReadSlice_Indx = NULL;
   (*env)->DeleteGlobalRef(env, gdxDataReadSlice_Vals); gdxDataReadSlice_Vals = NULL;
   return rc_Free;
}


static void  GDX_CALLCONV dll_gdxDataReadRawFast_DP(const int Indx[], const double Vals[])
{
   JNIEnv *env;
   jclass cls;
   jmethodID mid;
   (*Cached_JVM)->AttachCurrentThread(Cached_JVM, (void**)&env, NULL);
   if (methodname_gdxDataReadRawFast_DP==NULL)
      printerr("Callback function name is nil","DP");
   if (classname_gdxDataReadRawFast_DP==NULL)
      printerr("Callback class name is nil","DP");
   cls = (*env)->FindClass(env,classname_gdxDataReadRawFast_DP);
   if (cls==NULL)
      printerr("Class not found",classname_gdxDataReadRawFast_DP);
   mid = (*env)->GetStaticMethodID(env, cls, methodname_gdxDataReadRawFast_DP, sig_gdxDataReadRawFast_DP);
   if (mid==NULL)
      printerr("Static method not found",methodname_gdxDataReadRawFast_DP);
   if (ReturnName == 1) {
      sprintf(ClassDotMethodName,"%s.%s",classname_gdxDataReadRawFast_DP,methodname_gdxDataReadRawFast_DP);
      return; }
   if(NULL == gdxDataReadRawFast_Indx) {
      jintArray local_Indx = (*env)->NewIntArray(env, GMS_MAX_INDEX_DIM);
      if (local_Indx == NULL) printerr("Out of memory", "JNI:NewIntArray");
      gdxDataReadRawFast_Indx = (*env)->NewGlobalRef(env, local_Indx);
      (*env)->DeleteLocalRef(env, local_Indx);
      if (gdxDataReadRawFast_Indx == NULL) printerr("Out of memory", "Global reference");
   }
   (*env)->SetIntArrayRegion(env, gdxDataReadRawFast_Indx, 0, GMS_MAX_INDEX_DIM, Indx);
   if(NULL == gdxDataReadRawFast_Vals) {
      jdoubleArray local_Vals = (*env)->NewDoubleArray(env, GMS_VAL_MAX);
      if (local_Vals == NULL) printerr("Out of memory", "JNI:NewDoubleArray");
      gdxDataReadRawFast_Vals = (*env)->NewGlobalRef(env, local_Vals);
      (*env)->DeleteLocalRef(env, local_Vals);
      if (gdxDataReadRawFast_Vals == NULL) printerr("Out of memory", "Global reference");
   }
   (*env)->SetDoubleArrayRegion(env, gdxDataReadRawFast_Vals, 0, GMS_VAL_MAX, Vals);
   (*env)->CallStaticVoidMethod(env, cls, mid, gdxDataReadRawFast_Indx, gdxDataReadRawFast_Vals);
}

static int  GDX_CALLCONV dll_gdxDataReadRawFastFilt_DP(const int Indx[], const double Vals[], void *Uptr)
{
   return 0;
}

static void  GDX_CALLCONV dll_gdxDataReadSlice_DP(const int Indx[], const double Vals[])
{
   JNIEnv *env;
   jclass cls;
   jmethodID mid;
   (*Cached_JVM)->AttachCurrentThread(Cached_JVM, (void**)&env, NULL);
   if (methodname_gdxDataReadSlice_DP==NULL)
      printerr("Callback function name is nil","DP");
   if (classname_gdxDataReadSlice_DP==NULL)
      printerr("Callback class name is nil","DP");
   cls = (*env)->FindClass(env,classname_gdxDataReadSlice_DP);
   if (cls==NULL)
      printerr("Class not found",classname_gdxDataReadSlice_DP);
   mid = (*env)->GetStaticMethodID(env, cls, methodname_gdxDataReadSlice_DP, sig_gdxDataReadSlice_DP);
   if (mid==NULL)
      printerr("Static method not found",methodname_gdxDataReadSlice_DP);
   if (ReturnName == 1) {
      sprintf(ClassDotMethodName,"%s.%s",classname_gdxDataReadSlice_DP,methodname_gdxDataReadSlice_DP);
      return; }
   if(NULL == gdxDataReadSlice_Indx) {
      jintArray local_Indx = (*env)->NewIntArray(env, GMS_MAX_INDEX_DIM);
      if (local_Indx == NULL) printerr("Out of memory", "JNI:NewIntArray");
      gdxDataReadSlice_Indx = (*env)->NewGlobalRef(env, local_Indx);
      (*env)->DeleteLocalRef(env, local_Indx);
      if (gdxDataReadSlice_Indx == NULL) printerr("Out of memory", "Global reference");
   }
   (*env)->SetIntArrayRegion(env, gdxDataReadSlice_Indx, 0, GMS_MAX_INDEX_DIM, Indx);
   if(NULL == gdxDataReadSlice_Vals) {
      jdoubleArray local_Vals = (*env)->NewDoubleArray(env, GMS_VAL_MAX);
      if (local_Vals == NULL) printerr("Out of memory", "JNI:NewDoubleArray");
      gdxDataReadSlice_Vals = (*env)->NewGlobalRef(env, local_Vals);
      (*env)->DeleteLocalRef(env, local_Vals);
      if (gdxDataReadSlice_Vals == NULL) printerr("Out of memory", "Global reference");
   }
   (*env)->SetDoubleArrayRegion(env, gdxDataReadSlice_Vals, 0, GMS_VAL_MAX, Vals);
   (*env)->CallStaticVoidMethod(env, cls, mid, gdxDataReadSlice_Indx, gdxDataReadSlice_Vals);
}

static void  GDX_CALLCONV dll_gdxGetDomainElements_DP(int RawIndex, int MappedIndex, void *Uptr)
{
   JNIEnv *env;
   jclass cls;
   jmethodID mid;
   u64_t local_Uptr;
   (*Cached_JVM)->AttachCurrentThread(Cached_JVM, (void**)&env, NULL);
   if (methodname_gdxGetDomainElements_DP==NULL)
      printerr("Callback function name is nil","DP");
   if (classname_gdxGetDomainElements_DP==NULL)
      printerr("Callback class name is nil","DP");
   cls = (*env)->FindClass(env,classname_gdxGetDomainElements_DP);
   if (cls==NULL)
      printerr("Class not found",classname_gdxGetDomainElements_DP);
   mid = (*env)->GetStaticMethodID(env, cls, methodname_gdxGetDomainElements_DP, sig_gdxGetDomainElements_DP);
   if (mid==NULL)
      printerr("Static method not found",methodname_gdxGetDomainElements_DP);
   if (ReturnName == 1) {
      sprintf(ClassDotMethodName,"%s.%s",classname_gdxGetDomainElements_DP,methodname_gdxGetDomainElements_DP);
      return; }
   local_Uptr.p = Uptr;
   (*env)->CallStaticVoidMethod(env, cls, mid, RawIndex, MappedIndex, local_Uptr.i);
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymAdd(JNIEnv *env, jobject obj, jstring AName, jstring Txt, jint AIndx)
{
   int rc_gdxAcronymAdd;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   char *local_Txt;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   local_Txt = (char *)(*env)->GetStringUTFChars(env, Txt, NULL);
   rc_gdxAcronymAdd = gdxAcronymAdd((gdxHandle_t)pgdx.p, local_AName, local_Txt, AIndx);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   (*env)->ReleaseStringUTFChars(env, Txt, local_Txt);
   return rc_gdxAcronymAdd;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymCount(JNIEnv *env, jobject obj)
{
   int rc_gdxAcronymCount;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxAcronymCount = gdxAcronymCount((gdxHandle_t)pgdx.p);
   return rc_gdxAcronymCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymGetInfo(JNIEnv *env, jobject obj, jint N, jobjectArray AName, jobjectArray Txt, jintArray AIndx)
{
   int rc_gdxAcronymGetInfo;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AName;
   char buffer_AName[256];
   jstring local_Txt;
   char buffer_Txt[256];
   int local_AIndx[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_AName[0] = '\0';
   buffer_Txt[0] = '\0';
   rc_gdxAcronymGetInfo = gdxAcronymGetInfo((gdxHandle_t)pgdx.p, N, buffer_AName, buffer_Txt, local_AIndx);
   local_AName = (*env)->NewStringUTF(env, buffer_AName);
   (*env)->SetObjectArrayElement(env, AName, 0, local_AName);
   local_Txt = (*env)->NewStringUTF(env, buffer_Txt);
   (*env)->SetObjectArrayElement(env, Txt, 0, local_Txt);
   (*env)->SetIntArrayRegion(env, AIndx, 0, 1, local_AIndx);
   return rc_gdxAcronymGetInfo;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymGetMapping(JNIEnv *env, jobject obj, jint N, jintArray orgIndx, jintArray newIndx, jintArray autoIndex)
{
   int rc_gdxAcronymGetMapping;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_orgIndx[1];
   int local_newIndx[1];
   int local_autoIndex[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxAcronymGetMapping = gdxAcronymGetMapping((gdxHandle_t)pgdx.p, N, local_orgIndx, local_newIndx, local_autoIndex);
   (*env)->SetIntArrayRegion(env, orgIndx, 0, 1, local_orgIndx);
   (*env)->SetIntArrayRegion(env, newIndx, 0, 1, local_newIndx);
   (*env)->SetIntArrayRegion(env, autoIndex, 0, 1, local_autoIndex);
   return rc_gdxAcronymGetMapping;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymIndex(JNIEnv *env, jobject obj, jdouble V)
{
   int rc_gdxAcronymIndex;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxAcronymIndex = gdxAcronymIndex((gdxHandle_t)pgdx.p, V);
   return rc_gdxAcronymIndex;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymName(JNIEnv *env, jobject obj, jdouble V, jobjectArray AName)
{
   int rc_gdxAcronymName;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AName;
   char buffer_AName[256];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_AName[0] = '\0';
   rc_gdxAcronymName = gdxAcronymName((gdxHandle_t)pgdx.p, V, buffer_AName);
   local_AName = (*env)->NewStringUTF(env, buffer_AName);
   (*env)->SetObjectArrayElement(env, AName, 0, local_AName);
   return rc_gdxAcronymName;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymNextNr(JNIEnv *env, jobject obj, jint NV)
{
   int rc_gdxAcronymNextNr;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxAcronymNextNr = gdxAcronymNextNr((gdxHandle_t)pgdx.p, NV);
   return rc_gdxAcronymNextNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AcronymSetInfo(JNIEnv *env, jobject obj, jint N, jstring AName, jstring Txt, jint AIndx)
{
   int rc_gdxAcronymSetInfo;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   char *local_Txt;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   local_Txt = (char *)(*env)->GetStringUTFChars(env, Txt, NULL);
   rc_gdxAcronymSetInfo = gdxAcronymSetInfo((gdxHandle_t)pgdx.p, N, local_AName, local_Txt, AIndx);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   (*env)->ReleaseStringUTFChars(env, Txt, local_Txt);
   return rc_gdxAcronymSetInfo;
}

JNIEXPORT jdouble JNICALL Java_com_gams_api_gdx_AcronymValue(JNIEnv *env, jobject obj, jint AIndx)
{
   double rc_gdxAcronymValue;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0.0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxAcronymValue = gdxAcronymValue((gdxHandle_t)pgdx.p, AIndx);
   return rc_gdxAcronymValue;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AddAlias(JNIEnv *env, jobject obj, jstring Id1, jstring Id2)
{
   int rc_gdxAddAlias;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_Id1;
   char *local_Id2;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Id1 = (char *)(*env)->GetStringUTFChars(env, Id1, NULL);
   local_Id2 = (char *)(*env)->GetStringUTFChars(env, Id2, NULL);
   rc_gdxAddAlias = gdxAddAlias((gdxHandle_t)pgdx.p, local_Id1, local_Id2);
   (*env)->ReleaseStringUTFChars(env, Id1, local_Id1);
   (*env)->ReleaseStringUTFChars(env, Id2, local_Id2);
   return rc_gdxAddAlias;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AddSetText(JNIEnv *env, jobject obj, jstring Txt, jintArray TxtNr)
{
   int rc_gdxAddSetText;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_Txt;
   int local_TxtNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Txt = (char *)(*env)->GetStringUTFChars(env, Txt, NULL);
   rc_gdxAddSetText = gdxAddSetText((gdxHandle_t)pgdx.p, local_Txt, local_TxtNr);
   (*env)->ReleaseStringUTFChars(env, Txt, local_Txt);
   (*env)->SetIntArrayRegion(env, TxtNr, 0, 1, local_TxtNr);
   return rc_gdxAddSetText;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_AutoConvert(JNIEnv *env, jobject obj, jint NV)
{
   int rc_gdxAutoConvert;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxAutoConvert = gdxAutoConvert((gdxHandle_t)pgdx.p, NV);
   return rc_gdxAutoConvert;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_Close(JNIEnv *env, jobject obj)
{
   int rc_gdxClose;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxClose = gdxClose((gdxHandle_t)pgdx.p);
   return rc_gdxClose;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataErrorCount(JNIEnv *env, jobject obj)
{
   int rc_gdxDataErrorCount;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxDataErrorCount = gdxDataErrorCount((gdxHandle_t)pgdx.p);
   return rc_gdxDataErrorCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataErrorRecord(JNIEnv *env, jobject obj, jint RecNr, jintArray KeyInt, jdoubleArray Values)
{
   int rc_gdxDataErrorRecord;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_KeyInt;
   double *local_Values;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_KeyInt = (*env)->GetIntArrayElements(env, KeyInt, NULL);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   rc_gdxDataErrorRecord = gdxDataErrorRecord((gdxHandle_t)pgdx.p, RecNr, local_KeyInt, local_Values);
   (*env)->ReleaseIntArrayElements(env, KeyInt, local_KeyInt, 0);
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   return rc_gdxDataErrorRecord;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataErrorRecordX(JNIEnv *env, jobject obj, jint RecNr, jintArray KeyInt, jdoubleArray Values)
{
   int rc_gdxDataErrorRecordX;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_KeyInt;
   double *local_Values;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_KeyInt = (*env)->GetIntArrayElements(env, KeyInt, NULL);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   rc_gdxDataErrorRecordX = gdxDataErrorRecordX((gdxHandle_t)pgdx.p, RecNr, local_KeyInt, local_Values);
   (*env)->ReleaseIntArrayElements(env, KeyInt, local_KeyInt, 0);
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   return rc_gdxDataErrorRecordX;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadDone(JNIEnv *env, jobject obj)
{
   int rc_gdxDataReadDone;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxDataReadDone = gdxDataReadDone((gdxHandle_t)pgdx.p);
   return rc_gdxDataReadDone;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadFilteredStart(JNIEnv *env, jobject obj, jint SyNr, jintArray FilterAction, jintArray NrRecs)
{
   int rc_gdxDataReadFilteredStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_FilterAction;
   int local_NrRecs[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_FilterAction = (*env)->GetIntArrayElements(env, FilterAction, NULL);
   rc_gdxDataReadFilteredStart = gdxDataReadFilteredStart((gdxHandle_t)pgdx.p, SyNr, local_FilterAction, local_NrRecs);
   (*env)->ReleaseIntArrayElements(env, FilterAction, local_FilterAction, 0);
   (*env)->SetIntArrayRegion(env, NrRecs, 0, 1, local_NrRecs);
   return rc_gdxDataReadFilteredStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadMap(JNIEnv *env, jobject obj, jint RecNr, jintArray KeyInt, jdoubleArray Values, jintArray DimFrst)
{
   int rc_gdxDataReadMap;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_KeyInt;
   double *local_Values;
   int local_DimFrst[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_KeyInt = (*env)->GetIntArrayElements(env, KeyInt, NULL);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   rc_gdxDataReadMap = gdxDataReadMap((gdxHandle_t)pgdx.p, RecNr, local_KeyInt, local_Values, local_DimFrst);
   (*env)->ReleaseIntArrayElements(env, KeyInt, local_KeyInt, 0);
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   (*env)->SetIntArrayRegion(env, DimFrst, 0, 1, local_DimFrst);
   return rc_gdxDataReadMap;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadMapStart(JNIEnv *env, jobject obj, jint SyNr, jintArray NrRecs)
{
   int rc_gdxDataReadMapStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_NrRecs[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxDataReadMapStart = gdxDataReadMapStart((gdxHandle_t)pgdx.p, SyNr, local_NrRecs);
   (*env)->SetIntArrayRegion(env, NrRecs, 0, 1, local_NrRecs);
   return rc_gdxDataReadMapStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRaw(JNIEnv *env, jobject obj, jintArray KeyInt, jdoubleArray Values, jintArray DimFrst)
{
   int rc_gdxDataReadRaw;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_KeyInt;
   double *local_Values;
   int local_DimFrst[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_KeyInt = (*env)->GetIntArrayElements(env, KeyInt, NULL);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   rc_gdxDataReadRaw = gdxDataReadRaw((gdxHandle_t)pgdx.p, local_KeyInt, local_Values, local_DimFrst);
   (*env)->ReleaseIntArrayElements(env, KeyInt, local_KeyInt, 0);
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   (*env)->SetIntArrayRegion(env, DimFrst, 0, 1, local_DimFrst);
   return rc_gdxDataReadRaw;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRawFast(JNIEnv *env, jobject obj, jint SyNr, jstring DP, jintArray NrRecs)
{
   int rc_gdxDataReadRawFast;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_DP;
   int   have_DP = 0;
   TDataStoreProc_t ptr_DP = NULL;
   int local_NrRecs[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   if(DP != NULL)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     if(strcmp(local_DP,""))
       have_DP=1;
   }
   if(have_DP)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     methodname_gdxDataReadRawFast_DP = getMethodName_(local_DP);
     if(methodname_gdxDataReadRawFast_DP == NULL) printerr("Method name incomplete", local_DP);
     classname_gdxDataReadRawFast_DP = getClassName_(local_DP);
     if(classname_gdxDataReadRawFast_DP == NULL) printerr("Class name incomplete", local_DP);
     sig_gdxDataReadRawFast_DP = "([I[D)V";
     ptr_DP=dll_gdxDataReadRawFast_DP;
   }
   rc_gdxDataReadRawFast = gdxDataReadRawFast((gdxHandle_t)pgdx.p, SyNr, ptr_DP, local_NrRecs);
   if(DP != NULL)
      (*env)->ReleaseStringUTFChars(env, DP, local_DP);
   (*env)->SetIntArrayRegion(env, NrRecs, 0, 1, local_NrRecs);
   return rc_gdxDataReadRawFast;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRawFastFilt(JNIEnv *env, jobject obj, jint SyNr, jobjectArray UelFilterStr, jstring DP)
{
   int rc_gdxDataReadRawFastFilt;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int i_UelFilterStr, sidim_UelFilterStr;
   stringUEL local_UelFilterStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_UelFilterStr[GLOBAL_MAX_INDEX_DIM];
   char *local_DP;
   int   have_DP = 0;
   TDataStoreFiltProc_t ptr_DP = NULL;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   if(DP != NULL)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     if(strcmp(local_DP,""))
       have_DP=1;
   }
   if(have_DP)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     methodname_gdxDataReadRawFastFilt_DP = getMethodName_(local_DP);
     if(methodname_gdxDataReadRawFastFilt_DP == NULL) printerr("Method name incomplete", local_DP);
     classname_gdxDataReadRawFastFilt_DP = getClassName_(local_DP);
     if(classname_gdxDataReadRawFastFilt_DP == NULL) printerr("Class name incomplete", local_DP);
     sig_gdxDataReadRawFastFilt_DP = "([I[DJ)I";
     ptr_DP=dll_gdxDataReadRawFastFilt_DP;
   }
   sidim_UelFilterStr = gdxCurrentDim((gdxHandle_t)pgdx.p);
   for(i_UelFilterStr=0;i_UelFilterStr<sidim_UelFilterStr;++i_UelFilterStr) {
      jstring js_;
      char *str_;
      ptr_UelFilterStr[i_UelFilterStr] = local_UelFilterStr[i_UelFilterStr];
      js_ = (*env)->GetObjectArrayElement(env, UelFilterStr, i_UelFilterStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_UelFilterStr[i_UelFilterStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_UelFilterStr[i_UelFilterStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gdxDataReadRawFastFilt = gdxDataReadRawFastFilt((gdxHandle_t)pgdx.p, SyNr, (const char **)ptr_UelFilterStr, ptr_DP);
   if(DP != NULL)
      (*env)->ReleaseStringUTFChars(env, DP, local_DP);
   return rc_gdxDataReadRawFastFilt;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadRawStart(JNIEnv *env, jobject obj, jint SyNr, jintArray NrRecs)
{
   int rc_gdxDataReadRawStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_NrRecs[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxDataReadRawStart = gdxDataReadRawStart((gdxHandle_t)pgdx.p, SyNr, local_NrRecs);
   (*env)->SetIntArrayRegion(env, NrRecs, 0, 1, local_NrRecs);
   return rc_gdxDataReadRawStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadSlice(JNIEnv *env, jobject obj, jobjectArray UelFilterStr, jintArray Dimen, jstring DP)
{
   int rc_gdxDataReadSlice;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int i_UelFilterStr, sidim_UelFilterStr;
   stringUEL local_UelFilterStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_UelFilterStr[GLOBAL_MAX_INDEX_DIM];
   int local_Dimen[1];
   char *local_DP;
   int   have_DP = 0;
   TDataStoreProc_t ptr_DP = NULL;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   if(DP != NULL)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     if(strcmp(local_DP,""))
       have_DP=1;
   }
   if(have_DP)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     methodname_gdxDataReadSlice_DP = getMethodName_(local_DP);
     if(methodname_gdxDataReadSlice_DP == NULL) printerr("Method name incomplete", local_DP);
     classname_gdxDataReadSlice_DP = getClassName_(local_DP);
     if(classname_gdxDataReadSlice_DP == NULL) printerr("Class name incomplete", local_DP);
     sig_gdxDataReadSlice_DP = "([I[D)V";
     ptr_DP=dll_gdxDataReadSlice_DP;
   }
   sidim_UelFilterStr = gdxCurrentDim((gdxHandle_t)pgdx.p);
   for(i_UelFilterStr=0;i_UelFilterStr<sidim_UelFilterStr;++i_UelFilterStr) {
      jstring js_;
      char *str_;
      ptr_UelFilterStr[i_UelFilterStr] = local_UelFilterStr[i_UelFilterStr];
      js_ = (*env)->GetObjectArrayElement(env, UelFilterStr, i_UelFilterStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_UelFilterStr[i_UelFilterStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_UelFilterStr[i_UelFilterStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gdxDataReadSlice = gdxDataReadSlice((gdxHandle_t)pgdx.p, (const char **)ptr_UelFilterStr, local_Dimen, ptr_DP);
   (*env)->SetIntArrayRegion(env, Dimen, 0, 1, local_Dimen);
   if(DP != NULL)
      (*env)->ReleaseStringUTFChars(env, DP, local_DP);
   return rc_gdxDataReadSlice;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadSliceStart(JNIEnv *env, jobject obj, jint SyNr, jintArray ElemCounts)
{
   int rc_gdxDataReadSliceStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_ElemCounts;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_ElemCounts = (*env)->GetIntArrayElements(env, ElemCounts, NULL);
   rc_gdxDataReadSliceStart = gdxDataReadSliceStart((gdxHandle_t)pgdx.p, SyNr, local_ElemCounts);
   (*env)->ReleaseIntArrayElements(env, ElemCounts, local_ElemCounts, 0);
   return rc_gdxDataReadSliceStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadStr(JNIEnv *env, jobject obj, jobjectArray KeyStr, jdoubleArray Values, jintArray DimFrst)
{
   int rc_gdxDataReadStr;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int i_KeyStr, sidim_KeyStr;
   stringUEL local_KeyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_KeyStr[GLOBAL_MAX_INDEX_DIM];
   double *local_Values;
   int local_DimFrst[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   sidim_KeyStr = gdxCurrentDim((gdxHandle_t)pgdx.p);
   for(i_KeyStr=0;i_KeyStr<sidim_KeyStr;++i_KeyStr) {
      ptr_KeyStr[i_KeyStr] = local_KeyStr[i_KeyStr];
   }
   rc_gdxDataReadStr = gdxDataReadStr((gdxHandle_t)pgdx.p, ptr_KeyStr, local_Values, local_DimFrst);
   sidim_KeyStr = gdxCurrentDim((gdxHandle_t)pgdx.p);
   if(rc_gdxDataReadStr != 0)
   for(i_KeyStr=0;i_KeyStr<sidim_KeyStr;++i_KeyStr) {
      jstring js_;
      js_ = (*env)->NewStringUTF(env, local_KeyStr[i_KeyStr]);
      (*env)->SetObjectArrayElement(env, KeyStr, i_KeyStr, js_);
   }
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   (*env)->SetIntArrayRegion(env, DimFrst, 0, 1, local_DimFrst);
   return rc_gdxDataReadStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataReadStrStart(JNIEnv *env, jobject obj, jint SyNr, jintArray NrRecs)
{
   int rc_gdxDataReadStrStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_NrRecs[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxDataReadStrStart = gdxDataReadStrStart((gdxHandle_t)pgdx.p, SyNr, local_NrRecs);
   (*env)->SetIntArrayRegion(env, NrRecs, 0, 1, local_NrRecs);
   return rc_gdxDataReadStrStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataSliceUELS(JNIEnv *env, jobject obj, jintArray SliceKeyInt, jobjectArray KeyStr)
{
   int rc_gdxDataSliceUELS;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_SliceKeyInt;
   int i_KeyStr, sidim_KeyStr;
   stringUEL local_KeyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_KeyStr[GLOBAL_MAX_INDEX_DIM];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_SliceKeyInt = (*env)->GetIntArrayElements(env, SliceKeyInt, NULL);
   sidim_KeyStr = gdxCurrentDim((gdxHandle_t)pgdx.p);
   for(i_KeyStr=0;i_KeyStr<sidim_KeyStr;++i_KeyStr) {
      ptr_KeyStr[i_KeyStr] = local_KeyStr[i_KeyStr];
   }
   rc_gdxDataSliceUELS = gdxDataSliceUELS((gdxHandle_t)pgdx.p, local_SliceKeyInt, ptr_KeyStr);
   (*env)->ReleaseIntArrayElements(env, SliceKeyInt, local_SliceKeyInt, 0);
   sidim_KeyStr = gdxCurrentDim((gdxHandle_t)pgdx.p);
   if(rc_gdxDataSliceUELS != 0)
   for(i_KeyStr=0;i_KeyStr<sidim_KeyStr;++i_KeyStr) {
      jstring js_;
      js_ = (*env)->NewStringUTF(env, local_KeyStr[i_KeyStr]);
      (*env)->SetObjectArrayElement(env, KeyStr, i_KeyStr, js_);
   }
   return rc_gdxDataSliceUELS;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteDone(JNIEnv *env, jobject obj)
{
   int rc_gdxDataWriteDone;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxDataWriteDone = gdxDataWriteDone((gdxHandle_t)pgdx.p);
   return rc_gdxDataWriteDone;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteMap(JNIEnv *env, jobject obj, jintArray KeyInt, jdoubleArray Values)
{
   int rc_gdxDataWriteMap;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_KeyInt;
   double *local_Values;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_KeyInt = (*env)->GetIntArrayElements(env, KeyInt, NULL);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   rc_gdxDataWriteMap = gdxDataWriteMap((gdxHandle_t)pgdx.p, local_KeyInt, local_Values);
   (*env)->ReleaseIntArrayElements(env, KeyInt, local_KeyInt, 0);
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   return rc_gdxDataWriteMap;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteMapStart(JNIEnv *env, jobject obj, jstring SyId, jstring ExplTxt, jint Dimen, jint Typ, jint UserInfo)
{
   int rc_gdxDataWriteMapStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_SyId;
   char *local_ExplTxt;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_SyId = (char *)(*env)->GetStringUTFChars(env, SyId, NULL);
   local_ExplTxt = (char *)(*env)->GetStringUTFChars(env, ExplTxt, NULL);
   rc_gdxDataWriteMapStart = gdxDataWriteMapStart((gdxHandle_t)pgdx.p, local_SyId, local_ExplTxt, Dimen, Typ, UserInfo);
   (*env)->ReleaseStringUTFChars(env, SyId, local_SyId);
   (*env)->ReleaseStringUTFChars(env, ExplTxt, local_ExplTxt);
   return rc_gdxDataWriteMapStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteRaw(JNIEnv *env, jobject obj, jintArray KeyInt, jdoubleArray Values)
{
   int rc_gdxDataWriteRaw;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_KeyInt;
   double *local_Values;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_KeyInt = (*env)->GetIntArrayElements(env, KeyInt, NULL);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   rc_gdxDataWriteRaw = gdxDataWriteRaw((gdxHandle_t)pgdx.p, local_KeyInt, local_Values);
   (*env)->ReleaseIntArrayElements(env, KeyInt, local_KeyInt, 0);
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   return rc_gdxDataWriteRaw;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteRawStart(JNIEnv *env, jobject obj, jstring SyId, jstring ExplTxt, jint Dimen, jint Typ, jint UserInfo)
{
   int rc_gdxDataWriteRawStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_SyId;
   char *local_ExplTxt;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_SyId = (char *)(*env)->GetStringUTFChars(env, SyId, NULL);
   local_ExplTxt = (char *)(*env)->GetStringUTFChars(env, ExplTxt, NULL);
   rc_gdxDataWriteRawStart = gdxDataWriteRawStart((gdxHandle_t)pgdx.p, local_SyId, local_ExplTxt, Dimen, Typ, UserInfo);
   (*env)->ReleaseStringUTFChars(env, SyId, local_SyId);
   (*env)->ReleaseStringUTFChars(env, ExplTxt, local_ExplTxt);
   return rc_gdxDataWriteRawStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteStr(JNIEnv *env, jobject obj, jobjectArray KeyStr, jdoubleArray Values)
{
   int rc_gdxDataWriteStr;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int i_KeyStr, sidim_KeyStr;
   stringUEL local_KeyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_KeyStr[GLOBAL_MAX_INDEX_DIM];
   double *local_Values;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Values = (*env)->GetDoubleArrayElements(env, Values, NULL);
   sidim_KeyStr = gdxCurrentDim((gdxHandle_t)pgdx.p);
   for(i_KeyStr=0;i_KeyStr<sidim_KeyStr;++i_KeyStr) {
      jstring js_;
      char *str_;
      ptr_KeyStr[i_KeyStr] = local_KeyStr[i_KeyStr];
      js_ = (*env)->GetObjectArrayElement(env, KeyStr, i_KeyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_KeyStr[i_KeyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_KeyStr[i_KeyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gdxDataWriteStr = gdxDataWriteStr((gdxHandle_t)pgdx.p, (const char **)ptr_KeyStr, local_Values);
   (*env)->ReleaseDoubleArrayElements(env, Values, local_Values, 0);
   return rc_gdxDataWriteStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_DataWriteStrStart(JNIEnv *env, jobject obj, jstring SyId, jstring ExplTxt, jint Dimen, jint Typ, jint UserInfo)
{
   int rc_gdxDataWriteStrStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_SyId;
   char *local_ExplTxt;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_SyId = (char *)(*env)->GetStringUTFChars(env, SyId, NULL);
   local_ExplTxt = (char *)(*env)->GetStringUTFChars(env, ExplTxt, NULL);
   rc_gdxDataWriteStrStart = gdxDataWriteStrStart((gdxHandle_t)pgdx.p, local_SyId, local_ExplTxt, Dimen, Typ, UserInfo);
   (*env)->ReleaseStringUTFChars(env, SyId, local_SyId);
   (*env)->ReleaseStringUTFChars(env, ExplTxt, local_ExplTxt);
   return rc_gdxDataWriteStrStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetDLLVersion(JNIEnv *env, jobject obj, jobjectArray V)
{
   int rc_gdxGetDLLVersion;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_V;
   char buffer_V[256];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_V[0] = '\0';
   rc_gdxGetDLLVersion = gdxGetDLLVersion((gdxHandle_t)pgdx.p, buffer_V);
   local_V = (*env)->NewStringUTF(env, buffer_V);
   (*env)->SetObjectArrayElement(env, V, 0, local_V);
   return rc_gdxGetDLLVersion;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_ErrorCount(JNIEnv *env, jobject obj)
{
   int rc_gdxErrorCount;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxErrorCount = gdxErrorCount((gdxHandle_t)pgdx.p);
   return rc_gdxErrorCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_ErrorStr(JNIEnv *env, jobject obj, jint ErrNr, jobjectArray ErrMsg)
{
   int rc_gdxErrorStr;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_ErrMsg;
   char buffer_ErrMsg[256];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_ErrMsg[0] = '\0';
   rc_gdxErrorStr = gdxErrorStr((gdxHandle_t)pgdx.p, ErrNr, buffer_ErrMsg);
   local_ErrMsg = (*env)->NewStringUTF(env, buffer_ErrMsg);
   (*env)->SetObjectArrayElement(env, ErrMsg, 0, local_ErrMsg);
   return rc_gdxErrorStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FileInfo(JNIEnv *env, jobject obj, jintArray FileVer, jintArray ComprLev)
{
   int rc_gdxFileInfo;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_FileVer[1];
   int local_ComprLev[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxFileInfo = gdxFileInfo((gdxHandle_t)pgdx.p, local_FileVer, local_ComprLev);
   (*env)->SetIntArrayRegion(env, FileVer, 0, 1, local_FileVer);
   (*env)->SetIntArrayRegion(env, ComprLev, 0, 1, local_ComprLev);
   return rc_gdxFileInfo;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FileVersion(JNIEnv *env, jobject obj, jobjectArray FileStr, jobjectArray ProduceStr)
{
   int rc_gdxFileVersion;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_FileStr;
   char buffer_FileStr[256];
   jstring local_ProduceStr;
   char buffer_ProduceStr[256];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_FileStr[0] = '\0';
   buffer_ProduceStr[0] = '\0';
   rc_gdxFileVersion = gdxFileVersion((gdxHandle_t)pgdx.p, buffer_FileStr, buffer_ProduceStr);
   local_FileStr = (*env)->NewStringUTF(env, buffer_FileStr);
   (*env)->SetObjectArrayElement(env, FileStr, 0, local_FileStr);
   local_ProduceStr = (*env)->NewStringUTF(env, buffer_ProduceStr);
   (*env)->SetObjectArrayElement(env, ProduceStr, 0, local_ProduceStr);
   return rc_gdxFileVersion;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterExists(JNIEnv *env, jobject obj, jint FilterNr)
{
   int rc_gdxFilterExists;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxFilterExists = gdxFilterExists((gdxHandle_t)pgdx.p, FilterNr);
   return rc_gdxFilterExists;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterRegister(JNIEnv *env, jobject obj, jint UelMap)
{
   int rc_gdxFilterRegister;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxFilterRegister = gdxFilterRegister((gdxHandle_t)pgdx.p, UelMap);
   return rc_gdxFilterRegister;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterRegisterDone(JNIEnv *env, jobject obj)
{
   int rc_gdxFilterRegisterDone;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxFilterRegisterDone = gdxFilterRegisterDone((gdxHandle_t)pgdx.p);
   return rc_gdxFilterRegisterDone;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FilterRegisterStart(JNIEnv *env, jobject obj, jint FilterNr)
{
   int rc_gdxFilterRegisterStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxFilterRegisterStart = gdxFilterRegisterStart((gdxHandle_t)pgdx.p, FilterNr);
   return rc_gdxFilterRegisterStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_FindSymbol(JNIEnv *env, jobject obj, jstring SyId, jintArray SyNr)
{
   int rc_gdxFindSymbol;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_SyId;
   int local_SyNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_SyId = (char *)(*env)->GetStringUTFChars(env, SyId, NULL);
   rc_gdxFindSymbol = gdxFindSymbol((gdxHandle_t)pgdx.p, local_SyId, local_SyNr);
   (*env)->ReleaseStringUTFChars(env, SyId, local_SyId);
   (*env)->SetIntArrayRegion(env, SyNr, 0, 1, local_SyNr);
   return rc_gdxFindSymbol;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetElemText(JNIEnv *env, jobject obj, jint TxtNr, jobjectArray Txt, jintArray Node)
{
   int rc_gdxGetElemText;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_Txt;
   char buffer_Txt[256];
   int local_Node[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_Txt[0] = '\0';
   rc_gdxGetElemText = gdxGetElemText((gdxHandle_t)pgdx.p, TxtNr, buffer_Txt, local_Node);
   local_Txt = (*env)->NewStringUTF(env, buffer_Txt);
   (*env)->SetObjectArrayElement(env, Txt, 0, local_Txt);
   (*env)->SetIntArrayRegion(env, Node, 0, 1, local_Node);
   return rc_gdxGetElemText;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetLastError(JNIEnv *env, jobject obj)
{
   int rc_gdxGetLastError;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxGetLastError = gdxGetLastError((gdxHandle_t)pgdx.p);
   return rc_gdxGetLastError;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gdx_GetMemoryUsed(JNIEnv *env, jobject obj)
{
   INT64 rc_gdxGetMemoryUsed;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxGetMemoryUsed = gdxGetMemoryUsed((gdxHandle_t)pgdx.p);
   return rc_gdxGetMemoryUsed;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetSpecialValues(JNIEnv *env, jobject obj, jdoubleArray AVals)
{
   int rc_gdxGetSpecialValues;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   double *local_AVals;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_AVals = (*env)->GetDoubleArrayElements(env, AVals, NULL);
   rc_gdxGetSpecialValues = gdxGetSpecialValues((gdxHandle_t)pgdx.p, local_AVals);
   (*env)->ReleaseDoubleArrayElements(env, AVals, local_AVals, 0);
   return rc_gdxGetSpecialValues;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetUEL(JNIEnv *env, jobject obj, jint UelNr, jobjectArray Uel)
{
   int rc_gdxGetUEL;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_Uel;
   char buffer_Uel[256];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_Uel[0] = '\0';
   rc_gdxGetUEL = gdxGetUEL((gdxHandle_t)pgdx.p, UelNr, buffer_Uel);
   local_Uel = (*env)->NewStringUTF(env, buffer_Uel);
   (*env)->SetObjectArrayElement(env, Uel, 0, local_Uel);
   return rc_gdxGetUEL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_MapValue(JNIEnv *env, jobject obj, jdouble D, jintArray sv)
{
   int rc_gdxMapValue;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_sv[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxMapValue = gdxMapValue((gdxHandle_t)pgdx.p, D, local_sv);
   (*env)->SetIntArrayRegion(env, sv, 0, 1, local_sv);
   return rc_gdxMapValue;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenAppend(JNIEnv *env, jobject obj, jstring FileName, jstring Producer, jintArray ErrNr)
{
   int rc_gdxOpenAppend;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_FileName;
   char *local_Producer;
   int local_ErrNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_FileName = (char *)(*env)->GetStringUTFChars(env, FileName, NULL);
   local_Producer = (char *)(*env)->GetStringUTFChars(env, Producer, NULL);
   rc_gdxOpenAppend = gdxOpenAppend((gdxHandle_t)pgdx.p, local_FileName, local_Producer, local_ErrNr);
   (*env)->ReleaseStringUTFChars(env, FileName, local_FileName);
   (*env)->ReleaseStringUTFChars(env, Producer, local_Producer);
   (*env)->SetIntArrayRegion(env, ErrNr, 0, 1, local_ErrNr);
   return rc_gdxOpenAppend;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenRead(JNIEnv *env, jobject obj, jstring FileName, jintArray ErrNr)
{
   int rc_gdxOpenRead;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_FileName;
   int local_ErrNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_FileName = (char *)(*env)->GetStringUTFChars(env, FileName, NULL);
   rc_gdxOpenRead = gdxOpenRead((gdxHandle_t)pgdx.p, local_FileName, local_ErrNr);
   (*env)->ReleaseStringUTFChars(env, FileName, local_FileName);
   (*env)->SetIntArrayRegion(env, ErrNr, 0, 1, local_ErrNr);
   return rc_gdxOpenRead;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenReadEx(JNIEnv *env, jobject obj, jstring FileName, jint ReadMode, jintArray ErrNr)
{
   int rc_gdxOpenReadEx;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_FileName;
   int local_ErrNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_FileName = (char *)(*env)->GetStringUTFChars(env, FileName, NULL);
   rc_gdxOpenReadEx = gdxOpenReadEx((gdxHandle_t)pgdx.p, local_FileName, ReadMode, local_ErrNr);
   (*env)->ReleaseStringUTFChars(env, FileName, local_FileName);
   (*env)->SetIntArrayRegion(env, ErrNr, 0, 1, local_ErrNr);
   return rc_gdxOpenReadEx;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenWrite(JNIEnv *env, jobject obj, jstring FileName, jstring Producer, jintArray ErrNr)
{
   int rc_gdxOpenWrite;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_FileName;
   char *local_Producer;
   int local_ErrNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_FileName = (char *)(*env)->GetStringUTFChars(env, FileName, NULL);
   local_Producer = (char *)(*env)->GetStringUTFChars(env, Producer, NULL);
   rc_gdxOpenWrite = gdxOpenWrite((gdxHandle_t)pgdx.p, local_FileName, local_Producer, local_ErrNr);
   (*env)->ReleaseStringUTFChars(env, FileName, local_FileName);
   (*env)->ReleaseStringUTFChars(env, Producer, local_Producer);
   (*env)->SetIntArrayRegion(env, ErrNr, 0, 1, local_ErrNr);
   return rc_gdxOpenWrite;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_OpenWriteEx(JNIEnv *env, jobject obj, jstring FileName, jstring Producer, jint Compr, jintArray ErrNr)
{
   int rc_gdxOpenWriteEx;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_FileName;
   char *local_Producer;
   int local_ErrNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_FileName = (char *)(*env)->GetStringUTFChars(env, FileName, NULL);
   local_Producer = (char *)(*env)->GetStringUTFChars(env, Producer, NULL);
   rc_gdxOpenWriteEx = gdxOpenWriteEx((gdxHandle_t)pgdx.p, local_FileName, local_Producer, Compr, local_ErrNr);
   (*env)->ReleaseStringUTFChars(env, FileName, local_FileName);
   (*env)->ReleaseStringUTFChars(env, Producer, local_Producer);
   (*env)->SetIntArrayRegion(env, ErrNr, 0, 1, local_ErrNr);
   return rc_gdxOpenWriteEx;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_ResetSpecialValues(JNIEnv *env, jobject obj)
{
   int rc_gdxResetSpecialValues;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxResetSpecialValues = gdxResetSpecialValues((gdxHandle_t)pgdx.p);
   return rc_gdxResetSpecialValues;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetHasText(JNIEnv *env, jobject obj, jint SyNr)
{
   int rc_gdxSetHasText;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxSetHasText = gdxSetHasText((gdxHandle_t)pgdx.p, SyNr);
   return rc_gdxSetHasText;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetReadSpecialValues(JNIEnv *env, jobject obj, jdoubleArray AVals)
{
   int rc_gdxSetReadSpecialValues;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   double *local_AVals;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_AVals = (*env)->GetDoubleArrayElements(env, AVals, NULL);
   rc_gdxSetReadSpecialValues = gdxSetReadSpecialValues((gdxHandle_t)pgdx.p, local_AVals);
   (*env)->ReleaseDoubleArrayElements(env, AVals, local_AVals, 0);
   return rc_gdxSetReadSpecialValues;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetSpecialValues(JNIEnv *env, jobject obj, jdoubleArray AVals)
{
   int rc_gdxSetSpecialValues;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   double *local_AVals;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_AVals = (*env)->GetDoubleArrayElements(env, AVals, NULL);
   rc_gdxSetSpecialValues = gdxSetSpecialValues((gdxHandle_t)pgdx.p, local_AVals);
   (*env)->ReleaseDoubleArrayElements(env, AVals, local_AVals, 0);
   return rc_gdxSetSpecialValues;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetTextNodeNr(JNIEnv *env, jobject obj, jint TxtNr, jint Node)
{
   int rc_gdxSetTextNodeNr;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxSetTextNodeNr = gdxSetTextNodeNr((gdxHandle_t)pgdx.p, TxtNr, Node);
   return rc_gdxSetTextNodeNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SetTraceLevel(JNIEnv *env, jobject obj, jint N, jstring s)
{
   int rc_gdxSetTraceLevel;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_s;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_s = (char *)(*env)->GetStringUTFChars(env, s, NULL);
   rc_gdxSetTraceLevel = gdxSetTraceLevel((gdxHandle_t)pgdx.p, N, local_s);
   (*env)->ReleaseStringUTFChars(env, s, local_s);
   return rc_gdxSetTraceLevel;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbIndxMaxLength(JNIEnv *env, jobject obj, jint SyNr, jintArray LengthInfo)
{
   int rc_gdxSymbIndxMaxLength;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_LengthInfo;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_LengthInfo = (*env)->GetIntArrayElements(env, LengthInfo, NULL);
   rc_gdxSymbIndxMaxLength = gdxSymbIndxMaxLength((gdxHandle_t)pgdx.p, SyNr, local_LengthInfo);
   (*env)->ReleaseIntArrayElements(env, LengthInfo, local_LengthInfo, 0);
   return rc_gdxSymbIndxMaxLength;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbMaxLength(JNIEnv *env, jobject obj)
{
   int rc_gdxSymbMaxLength;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxSymbMaxLength = gdxSymbMaxLength((gdxHandle_t)pgdx.p);
   return rc_gdxSymbMaxLength;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolAddComment(JNIEnv *env, jobject obj, jint SyNr, jstring Txt)
{
   int rc_gdxSymbolAddComment;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_Txt;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Txt = (char *)(*env)->GetStringUTFChars(env, Txt, NULL);
   rc_gdxSymbolAddComment = gdxSymbolAddComment((gdxHandle_t)pgdx.p, SyNr, local_Txt);
   (*env)->ReleaseStringUTFChars(env, Txt, local_Txt);
   return rc_gdxSymbolAddComment;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolGetComment(JNIEnv *env, jobject obj, jint SyNr, jint N, jobjectArray Txt)
{
   int rc_gdxSymbolGetComment;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_Txt;
   char buffer_Txt[256];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_Txt[0] = '\0';
   rc_gdxSymbolGetComment = gdxSymbolGetComment((gdxHandle_t)pgdx.p, SyNr, N, buffer_Txt);
   local_Txt = (*env)->NewStringUTF(env, buffer_Txt);
   (*env)->SetObjectArrayElement(env, Txt, 0, local_Txt);
   return rc_gdxSymbolGetComment;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolGetDomain(JNIEnv *env, jobject obj, jint SyNr, jintArray DomainSyNrs)
{
   int rc_gdxSymbolGetDomain;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int *local_DomainSyNrs;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_DomainSyNrs = (*env)->GetIntArrayElements(env, DomainSyNrs, NULL);
   rc_gdxSymbolGetDomain = gdxSymbolGetDomain((gdxHandle_t)pgdx.p, SyNr, local_DomainSyNrs);
   (*env)->ReleaseIntArrayElements(env, DomainSyNrs, local_DomainSyNrs, 0);
   return rc_gdxSymbolGetDomain;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolGetDomainX(JNIEnv *env, jobject obj, jint SyNr, jobjectArray DomainIDs)
{
   int rc_gdxSymbolGetDomainX;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int i_DomainIDs, sidim_DomainIDs;
   stringUEL local_DomainIDs[GLOBAL_MAX_INDEX_DIM];
   char *ptr_DomainIDs[GLOBAL_MAX_INDEX_DIM];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   sidim_DomainIDs = gdxSymbolDim((gdxHandle_t)pgdx.p, SyNr);
   for(i_DomainIDs=0;i_DomainIDs<sidim_DomainIDs;++i_DomainIDs) {
      ptr_DomainIDs[i_DomainIDs] = local_DomainIDs[i_DomainIDs];
   }
   rc_gdxSymbolGetDomainX = gdxSymbolGetDomainX((gdxHandle_t)pgdx.p, SyNr, ptr_DomainIDs);
   sidim_DomainIDs = gdxSymbolDim((gdxHandle_t)pgdx.p, SyNr);
   if(rc_gdxSymbolGetDomainX != 0)
   for(i_DomainIDs=0;i_DomainIDs<sidim_DomainIDs;++i_DomainIDs) {
      jstring js_;
      js_ = (*env)->NewStringUTF(env, local_DomainIDs[i_DomainIDs]);
      (*env)->SetObjectArrayElement(env, DomainIDs, i_DomainIDs, js_);
   }
   return rc_gdxSymbolGetDomainX;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolDim(JNIEnv *env, jobject obj, jint SyNr)
{
   int rc_gdxSymbolDim;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxSymbolDim = gdxSymbolDim((gdxHandle_t)pgdx.p, SyNr);
   return rc_gdxSymbolDim;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolInfo(JNIEnv *env, jobject obj, jint SyNr, jobjectArray SyId, jintArray Dimen, jintArray Typ)
{
   int rc_gdxSymbolInfo;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_SyId;
   char buffer_SyId[256];
   int local_Dimen[1];
   int local_Typ[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_SyId[0] = '\0';
   rc_gdxSymbolInfo = gdxSymbolInfo((gdxHandle_t)pgdx.p, SyNr, buffer_SyId, local_Dimen, local_Typ);
   local_SyId = (*env)->NewStringUTF(env, buffer_SyId);
   (*env)->SetObjectArrayElement(env, SyId, 0, local_SyId);
   (*env)->SetIntArrayRegion(env, Dimen, 0, 1, local_Dimen);
   (*env)->SetIntArrayRegion(env, Typ, 0, 1, local_Typ);
   return rc_gdxSymbolInfo;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolInfoX(JNIEnv *env, jobject obj, jint SyNr, jintArray RecCnt, jintArray UserInfo, jobjectArray ExplTxt)
{
   int rc_gdxSymbolInfoX;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_RecCnt[1];
   int local_UserInfo[1];
   jstring local_ExplTxt;
   char buffer_ExplTxt[256];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_ExplTxt[0] = '\0';
   rc_gdxSymbolInfoX = gdxSymbolInfoX((gdxHandle_t)pgdx.p, SyNr, local_RecCnt, local_UserInfo, buffer_ExplTxt);
   (*env)->SetIntArrayRegion(env, RecCnt, 0, 1, local_RecCnt);
   (*env)->SetIntArrayRegion(env, UserInfo, 0, 1, local_UserInfo);
   local_ExplTxt = (*env)->NewStringUTF(env, buffer_ExplTxt);
   (*env)->SetObjectArrayElement(env, ExplTxt, 0, local_ExplTxt);
   return rc_gdxSymbolInfoX;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolSetDomain(JNIEnv *env, jobject obj, jobjectArray DomainIDs)
{
   int rc_gdxSymbolSetDomain;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int i_DomainIDs, sidim_DomainIDs;
   stringUEL local_DomainIDs[GLOBAL_MAX_INDEX_DIM];
   char *ptr_DomainIDs[GLOBAL_MAX_INDEX_DIM];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   sidim_DomainIDs = gdxCurrentDim((gdxHandle_t)pgdx.p);
   for(i_DomainIDs=0;i_DomainIDs<sidim_DomainIDs;++i_DomainIDs) {
      jstring js_;
      char *str_;
      ptr_DomainIDs[i_DomainIDs] = local_DomainIDs[i_DomainIDs];
      js_ = (*env)->GetObjectArrayElement(env, DomainIDs, i_DomainIDs);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_DomainIDs[i_DomainIDs], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_DomainIDs[i_DomainIDs][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gdxSymbolSetDomain = gdxSymbolSetDomain((gdxHandle_t)pgdx.p, (const char **)ptr_DomainIDs);
   return rc_gdxSymbolSetDomain;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SymbolSetDomainX(JNIEnv *env, jobject obj, jint SyNr, jobjectArray DomainIDs)
{
   int rc_gdxSymbolSetDomainX;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int i_DomainIDs, sidim_DomainIDs;
   stringUEL local_DomainIDs[GLOBAL_MAX_INDEX_DIM];
   char *ptr_DomainIDs[GLOBAL_MAX_INDEX_DIM];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   sidim_DomainIDs = gdxSymbolDim((gdxHandle_t)pgdx.p, SyNr);
   for(i_DomainIDs=0;i_DomainIDs<sidim_DomainIDs;++i_DomainIDs) {
      jstring js_;
      char *str_;
      ptr_DomainIDs[i_DomainIDs] = local_DomainIDs[i_DomainIDs];
      js_ = (*env)->GetObjectArrayElement(env, DomainIDs, i_DomainIDs);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_DomainIDs[i_DomainIDs], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_DomainIDs[i_DomainIDs][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gdxSymbolSetDomainX = gdxSymbolSetDomainX((gdxHandle_t)pgdx.p, SyNr, (const char **)ptr_DomainIDs);
   return rc_gdxSymbolSetDomainX;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_SystemInfo(JNIEnv *env, jobject obj, jintArray SyCnt, jintArray UelCnt)
{
   int rc_gdxSystemInfo;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_SyCnt[1];
   int local_UelCnt[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxSystemInfo = gdxSystemInfo((gdxHandle_t)pgdx.p, local_SyCnt, local_UelCnt);
   (*env)->SetIntArrayRegion(env, SyCnt, 0, 1, local_SyCnt);
   (*env)->SetIntArrayRegion(env, UelCnt, 0, 1, local_UelCnt);
   return rc_gdxSystemInfo;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELMaxLength(JNIEnv *env, jobject obj)
{
   int rc_gdxUELMaxLength;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxUELMaxLength = gdxUELMaxLength((gdxHandle_t)pgdx.p);
   return rc_gdxUELMaxLength;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterDone(JNIEnv *env, jobject obj)
{
   int rc_gdxUELRegisterDone;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxUELRegisterDone = gdxUELRegisterDone((gdxHandle_t)pgdx.p);
   return rc_gdxUELRegisterDone;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterMap(JNIEnv *env, jobject obj, jint UMap, jstring Uel)
{
   int rc_gdxUELRegisterMap;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_Uel;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Uel = (char *)(*env)->GetStringUTFChars(env, Uel, NULL);
   rc_gdxUELRegisterMap = gdxUELRegisterMap((gdxHandle_t)pgdx.p, UMap, local_Uel);
   (*env)->ReleaseStringUTFChars(env, Uel, local_Uel);
   return rc_gdxUELRegisterMap;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterMapStart(JNIEnv *env, jobject obj)
{
   int rc_gdxUELRegisterMapStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxUELRegisterMapStart = gdxUELRegisterMapStart((gdxHandle_t)pgdx.p);
   return rc_gdxUELRegisterMapStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterRaw(JNIEnv *env, jobject obj, jstring Uel)
{
   int rc_gdxUELRegisterRaw;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_Uel;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Uel = (char *)(*env)->GetStringUTFChars(env, Uel, NULL);
   rc_gdxUELRegisterRaw = gdxUELRegisterRaw((gdxHandle_t)pgdx.p, local_Uel);
   (*env)->ReleaseStringUTFChars(env, Uel, local_Uel);
   return rc_gdxUELRegisterRaw;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterRawStart(JNIEnv *env, jobject obj)
{
   int rc_gdxUELRegisterRawStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxUELRegisterRawStart = gdxUELRegisterRawStart((gdxHandle_t)pgdx.p);
   return rc_gdxUELRegisterRawStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterStr(JNIEnv *env, jobject obj, jstring Uel, jintArray UelNr)
{
   int rc_gdxUELRegisterStr;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_Uel;
   int local_UelNr[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Uel = (char *)(*env)->GetStringUTFChars(env, Uel, NULL);
   rc_gdxUELRegisterStr = gdxUELRegisterStr((gdxHandle_t)pgdx.p, local_Uel, local_UelNr);
   (*env)->ReleaseStringUTFChars(env, Uel, local_Uel);
   (*env)->SetIntArrayRegion(env, UelNr, 0, 1, local_UelNr);
   return rc_gdxUELRegisterStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UELRegisterStrStart(JNIEnv *env, jobject obj)
{
   int rc_gdxUELRegisterStrStart;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxUELRegisterStrStart = gdxUELRegisterStrStart((gdxHandle_t)pgdx.p);
   return rc_gdxUELRegisterStrStart;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UMFindUEL(JNIEnv *env, jobject obj, jstring Uel, jintArray UelNr, jintArray UelMap)
{
   int rc_gdxUMFindUEL;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_Uel;
   int local_UelNr[1];
   int local_UelMap[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_Uel = (char *)(*env)->GetStringUTFChars(env, Uel, NULL);
   rc_gdxUMFindUEL = gdxUMFindUEL((gdxHandle_t)pgdx.p, local_Uel, local_UelNr, local_UelMap);
   (*env)->ReleaseStringUTFChars(env, Uel, local_Uel);
   (*env)->SetIntArrayRegion(env, UelNr, 0, 1, local_UelNr);
   (*env)->SetIntArrayRegion(env, UelMap, 0, 1, local_UelMap);
   return rc_gdxUMFindUEL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UMUelGet(JNIEnv *env, jobject obj, jint UelNr, jobjectArray Uel, jintArray UelMap)
{
   int rc_gdxUMUelGet;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_Uel;
   char buffer_Uel[256];
   int local_UelMap[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   buffer_Uel[0] = '\0';
   rc_gdxUMUelGet = gdxUMUelGet((gdxHandle_t)pgdx.p, UelNr, buffer_Uel, local_UelMap);
   local_Uel = (*env)->NewStringUTF(env, buffer_Uel);
   (*env)->SetObjectArrayElement(env, Uel, 0, local_Uel);
   (*env)->SetIntArrayRegion(env, UelMap, 0, 1, local_UelMap);
   return rc_gdxUMUelGet;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_UMUelInfo(JNIEnv *env, jobject obj, jintArray UelCnt, jintArray HighMap)
{
   int rc_gdxUMUelInfo;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_UelCnt[1];
   int local_HighMap[1];
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxUMUelInfo = gdxUMUelInfo((gdxHandle_t)pgdx.p, local_UelCnt, local_HighMap);
   (*env)->SetIntArrayRegion(env, UelCnt, 0, 1, local_UelCnt);
   (*env)->SetIntArrayRegion(env, HighMap, 0, 1, local_HighMap);
   return rc_gdxUMUelInfo;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_GetDomainElements(JNIEnv *env, jobject obj, jint SyNr, jint DimPos, jint FilterNr, jstring DP, jintArray NrElem, jlong Uptr)
{
   int rc_gdxGetDomainElements;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_DP;
   int   have_DP = 0;
   TDomainIndexProc_t ptr_DP = NULL;
   int local_NrElem[1];
   u64_t local_Uptr;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   if(DP != NULL)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     if(strcmp(local_DP,""))
       have_DP=1;
   }
   if(have_DP)
   {
     local_DP = (char *)(*env)->GetStringUTFChars(env, DP, NULL);
     methodname_gdxGetDomainElements_DP = getMethodName_(local_DP);
     if(methodname_gdxGetDomainElements_DP == NULL) printerr("Method name incomplete", local_DP);
     classname_gdxGetDomainElements_DP = getClassName_(local_DP);
     if(classname_gdxGetDomainElements_DP == NULL) printerr("Class name incomplete", local_DP);
     sig_gdxGetDomainElements_DP = "(IIJ)V";
     ptr_DP=dll_gdxGetDomainElements_DP;
   }
   local_Uptr.i = Uptr;
   rc_gdxGetDomainElements = gdxGetDomainElements((gdxHandle_t)pgdx.p, SyNr, DimPos, FilterNr, ptr_DP, local_NrElem, local_Uptr.p);
   if(DP != NULL)
      (*env)->ReleaseStringUTFChars(env, DP, local_DP);
   (*env)->SetIntArrayRegion(env, NrElem, 0, 1, local_NrElem);
   return rc_gdxGetDomainElements;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_CurrentDim(JNIEnv *env, jobject obj)
{
   int rc_gdxCurrentDim;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   rc_gdxCurrentDim = gdxCurrentDim((gdxHandle_t)pgdx.p);
   return rc_gdxCurrentDim;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gdx_RenameUEL(JNIEnv *env, jobject obj, jstring OldName, jstring NewName)
{
   int rc_gdxRenameUEL;
   jfieldID fid;
   u64_t pgdx;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_OldName;
   char *local_NewName;
   fid = (*env)->GetFieldID(env, cls, "gdxPtr", "J");
   if (fid == NULL) return 0;
   pgdx.i = (*env)->GetLongField(env, obj, fid);
   local_OldName = (char *)(*env)->GetStringUTFChars(env, OldName, NULL);
   local_NewName = (char *)(*env)->GetStringUTFChars(env, NewName, NULL);
   rc_gdxRenameUEL = gdxRenameUEL((gdxHandle_t)pgdx.p, local_OldName, local_NewName);
   (*env)->ReleaseStringUTFChars(env, OldName, local_OldName);
   (*env)->ReleaseStringUTFChars(env, NewName, local_NewName);
   return rc_gdxRenameUEL;
}
