/*  Java Native Interrface code generated by apiwrapper for GAMS Version 30.1.0
 *
 * GAMS - Loading mechanism for GAMS Expert-Level APIs
 *
 * Copyright (c) 2016-2020 GAMS Software GmbH <support@gams.com>
 * Copyright (c) 2016-2020 GAMS Development Corp. <support@gams.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* #include <locale.h> */
#include <optcc.h>

/* at least for some JNI implementations, JNIEXPORT is not setup to
 * explicitly set visibility to default when using GNU compilers;
 * thus, we do this globally for all functions via this pragma
 *  (which is nicer than redefining JNIEXPORT)
 */
#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif

typedef union foo { void *p; jlong i; } u64_t;

typedef char string255[256];
static char* sig_optReadFromCmdArgs_cb = NULL;
static char* methodname_optReadFromCmdArgs_cb = NULL;
static char* classname_optReadFromCmdArgs_cb = NULL;
static char  ClassDotMethodName[512];
static int   ReturnName = 0;

static void printerr(const char *mess, const char*name)
{
   fprintf(stderr,"%s: %s\n",mess,name);
   exit(1);
}

static char* getMethodName_(const char* name)
{
    char *s;
    s = strrchr(name,'.');
    if (s==NULL)
        return NULL;
    ++s;
    return strdup(s);
}

static char* getClassName_(const char* name)
{
    char *s;
    char *t;
    t = strdup(name);
    s = strrchr(t,'.');
    if (s==NULL)
        return NULL;
    *s = '\0';
    return t;
}

static JavaVM *Cached_JVM = NULL;
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved)
{
    Cached_JVM = vm;
    optInitMutexes();
    return JNI_VERSION_1_2;
}

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM *vm, void *reserved)
{
    optFiniMutexes();
}

/* Prototypes */
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetReady(JNIEnv *env, jobject obj, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetReadyD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetReadyL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_Create(JNIEnv *env, jobject obj, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_CreateD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_CreateL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_Free(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadDefinition(JNIEnv *env, jobject obj, jstring fn);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadDefinitionFromPChar(JNIEnv *env, jobject obj, jobjectArray p);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadParameterFile(JNIEnv *env, jobject obj, jstring fn);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromStr(JNIEnv *env, jobject obj, jstring s);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_WriteParameterFile(JNIEnv *env, jobject obj, jstring fn);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ClearMessages(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_gams_api_opt_AddMessage(JNIEnv *env, jobject obj, jstring info);
JNIEXPORT void JNICALL Java_com_gams_api_opt_GetMessage(JNIEnv *env, jobject obj, jint NrMsg, jobjectArray info, jintArray iType);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ResetAll(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ResetAllRecent(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ResetRecentChanges(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ShowHelp(JNIEnv *env, jobject obj, jstring AHlpID);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_ResetNr(JNIEnv *env, jobject obj, jint ANr);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_FindStr(JNIEnv *env, jobject obj, jstring AName, jintArray ANr, jintArray ARefNr);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetInfoNr(JNIEnv *env, jobject obj, jint ANr, jintArray ADefined, jintArray ADefinedR, jintArray ARefNr, jintArray ADataType, jintArray AOptType, jintArray ASubType);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetValuesNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASName, jintArray AIVal, jdoubleArray ADVal, jobjectArray ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetValuesNr(JNIEnv *env, jobject obj, jint ANr, jint AIVal, jdouble ADVal, jstring ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetValues2Nr(JNIEnv *env, jobject obj, jint ANr, jint AIVal, jdouble ADVal, jstring ASVal);
JNIEXPORT void JNICALL Java_com_gams_api_opt_Version(JNIEnv *env, jobject obj, jobjectArray sversion);
JNIEXPORT void JNICALL Java_com_gams_api_opt_DefinitionFile(JNIEnv *env, jobject obj, jobjectArray sfilename);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetFromAnyStrList(JNIEnv *env, jobject obj, jint idash, jobjectArray skey, jobjectArray sval);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetFromListStr(JNIEnv *env, jobject obj, jstring skey, jobjectArray sval);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_ListCountStr(JNIEnv *env, jobject obj, jstring skey);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadFromListStr(JNIEnv *env, jobject obj, jstring skey, jint iPos, jobjectArray sval);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SynonymCount(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetSynonym(JNIEnv *env, jobject obj, jint NrSyn, jobjectArray SSyn, jobjectArray SName);
JNIEXPORT void JNICALL Java_com_gams_api_opt_EchoSet(JNIEnv *env, jobject obj, jint AIVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_EOLOnlySet(JNIEnv *env, jobject obj, jint AIVal);
JNIEXPORT void JNICALL Java_com_gams_api_opt_NoBoundsSet(JNIEnv *env, jobject obj, jint AIVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_EOLChars(JNIEnv *env, jobject obj, jobjectArray EOLChars);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ErrorCount(JNIEnv *env, jobject obj, jintArray iErrors, jintArray iWarnings);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetBoundsInt(JNIEnv *env, jobject obj, jint ANr, jintArray ilval, jintArray ihval, jintArray idval);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetBoundsDbl(JNIEnv *env, jobject obj, jint ANr, jdoubleArray dlval, jdoubleArray dhval, jdoubleArray ddval);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDefaultStr(JNIEnv *env, jobject obj, jint ANr, jobjectArray sval);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetIntNr(JNIEnv *env, jobject obj, jint ANr, jintArray AIVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetInt2Nr(JNIEnv *env, jobject obj, jint ANr, jintArray AIVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetIntNr(JNIEnv *env, jobject obj, jint ANr, jint AIVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetInt2Nr(JNIEnv *env, jobject obj, jint ANr, jint AIVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetStrNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetOptHelpNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray AName, jintArray AHc, jintArray AGroup);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumHelp(JNIEnv *env, jobject obj, jint ANr, jint AOrd, jintArray AHc, jobjectArray AHelpStr);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumStrNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASVal, jintArray AOrd);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumCount(JNIEnv *env, jobject obj, jint ANr, jintArray ACount);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumValue(JNIEnv *env, jobject obj, jint ANr, jint AOrd, jintArray AValInt, jobjectArray AValStr);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetStr2Nr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetStrNr(JNIEnv *env, jobject obj, jint ANr, jstring ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetStr2Nr(JNIEnv *env, jobject obj, jint ANr, jstring ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDblNr(JNIEnv *env, jobject obj, jint ANr, jdoubleArray ADVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDbl2Nr(JNIEnv *env, jobject obj, jint ANr, jdoubleArray ADVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetDblNr(JNIEnv *env, jobject obj, jint ANr, jdouble ADVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetDbl2Nr(JNIEnv *env, jobject obj, jint ANr, jdouble ADVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetValStr(JNIEnv *env, jobject obj, jstring AName, jobjectArray ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVal2Str(JNIEnv *env, jobject obj, jstring AName, jobjectArray ASVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetNameNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASName);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDefinedNr(JNIEnv *env, jobject obj, jint ANr, jintArray AIVal);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetHelpNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASOpt, jobjectArray ASHelp);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetGroupNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray AName, jintArray AGroup, jintArray AHc, jobjectArray AHelp);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetGroupGrpNr(JNIEnv *env, jobject obj, jint AGroup);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetOptGroupNr(JNIEnv *env, jobject obj, jint ANr);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDotOptNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray VEName, jintArray AObjNr, jintArray ADim, jdoubleArray AValue);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDotOptUel(JNIEnv *env, jobject obj, jint ANr, jint ADim, jobjectArray AUEL);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVarEquMapNr(JNIEnv *env, jobject obj, jint maptype, jint ANr, jobjectArray EquName, jobjectArray VarName, jintArray EquDim, jintArray VarDim, jintArray AValue);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEquVarEquMapNr(JNIEnv *env, jobject obj, jint maptype, jint ANr, jint ADim, jobjectArray AIndex);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVarVarEquMapNr(JNIEnv *env, jobject obj, jint maptype, jint ANr, jint ADim, jobjectArray AIndex);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_VarEquMapCount(JNIEnv *env, jobject obj, jint maptype, jintArray ANrErrors);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetIndicatorNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray EquName, jobjectArray VarName, jintArray EquDim, jintArray VarDim, jintArray AValue);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEquIndicatorNr(JNIEnv *env, jobject obj, jint ANr, jint ADim, jobjectArray AIndex);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVarIndicatorNr(JNIEnv *env, jobject obj, jint ANr, jint ADim, jobjectArray AIndex);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_IndicatorCount(JNIEnv *env, jobject obj, jintArray ANrErrors);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_DotOptCount(JNIEnv *env, jobject obj, jintArray ANrErrors);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetRefNr(JNIEnv *env, jobject obj, jint ANr, jint ARefNr);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetRefNrStr(JNIEnv *env, jobject obj, jstring AOpt, jint ARefNr);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetConstName(JNIEnv *env, jobject obj, jint cgroup, jint cindex, jobjectArray cname);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetTypeName(JNIEnv *env, jobject obj, jint TNr, jobjectArray sTName);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_LookUp(JNIEnv *env, jobject obj, jstring AOpt);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromPChar(JNIEnv *env, jobject obj, jobjectArray p);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromCmdLine(JNIEnv *env, jobject obj, jobjectArray p);
JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromCmdArgs(JNIEnv *env, jobject obj, jstring cb);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetNameOpt(JNIEnv *env, jobject obj, jstring ASVal, jobjectArray solver, jintArray opt);
JNIEXPORT jboolean JNICALL Java_com_gams_api_opt_ResetStr(JNIEnv *env, jobject obj, jstring AName);
JNIEXPORT jboolean JNICALL Java_com_gams_api_opt_GetDefinedStr(JNIEnv *env, jobject obj, jstring AName);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetIntStr(JNIEnv *env, jobject obj, jstring AName);
JNIEXPORT jdouble JNICALL Java_com_gams_api_opt_GetDblStr(JNIEnv *env, jobject obj, jstring AName);
JNIEXPORT jstring JNICALL Java_com_gams_api_opt_GetStrStr(JNIEnv *env, jobject obj, jstring AName, jobjectArray sst_result);
JNIEXPORT void JNICALL Java_com_gams_api_opt_SetIntStr(JNIEnv *env, jobject obj, jstring AName, jint AIVal);
JNIEXPORT void JNICALL Java_com_gams_api_opt_SetDblStr(JNIEnv *env, jobject obj, jstring AName, jdouble ADVal);
JNIEXPORT void JNICALL Java_com_gams_api_opt_SetStrStr(JNIEnv *env, jobject obj, jstring AName, jstring ASVal);
JNIEXPORT jboolean JNICALL Java_com_gams_api_opt_IsDeprecated(JNIEnv *env, jobject obj, jstring AName);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_Count(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_MessageCount(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_GroupCount(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_opt_RecentEnabled(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_com_gams_api_opt_RecentEnabledSet(JNIEnv *env, jobject obj, jint x);
JNIEXPORT jstring JNICALL Java_com_gams_api_opt_Separator(JNIEnv *env, jobject obj, jobjectArray sst_result);
JNIEXPORT jstring JNICALL Java_com_gams_api_opt_StringQuote(JNIEnv *env, jobject obj, jobjectArray sst_result);

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetReady(JNIEnv *env, jobject obj, jobjectArray msg)
{
   int rc_GetReady;
   jstring local_msg;
   char buffer_msg[256];
   rc_GetReady = optGetReady(buffer_msg, sizeof(buffer_msg));
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReady;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetReadyD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg)
{
   int rc_GetReadyD;
   char *local_dirName;
   jstring local_msg;
   char buffer_msg[256];
   buffer_msg[0] = '\0';
   local_dirName = (char *) (*env)->GetStringUTFChars(env, dirName, NULL);
   rc_GetReadyD = optGetReadyD(local_dirName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, dirName, local_dirName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReadyD;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetReadyL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg)
{
   int rc_GetReadyL;
   char *local_libName;
   jstring local_msg;
   char buffer_msg[256];
   buffer_msg[0] = '\0';
   local_libName = (char *) (*env)->GetStringUTFChars(env, libName, NULL);
   rc_GetReadyL = optGetReadyL(local_libName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, libName, local_libName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReadyL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_Create(JNIEnv *env, jobject obj, jobjectArray msg)
{
   int rc_Create;
   jfieldID fid;
   u64_t popt;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_Create = optCreate((optHandle_t *)&popt.p, buffer_msg, sizeof(buffer_msg));
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, popt.i);
   return rc_Create;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_CreateD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg)
{
   int rc_CreateD;
   jfieldID fid;
   u64_t popt;
   char *local_dirName;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_dirName = (char *) (*env)->GetStringUTFChars(env, dirName, NULL);
   rc_CreateD = optCreateD((optHandle_t *)&popt.p, local_dirName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, dirName, local_dirName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, popt.i);
   return rc_CreateD;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_CreateL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg)
{
   int rc_CreateL;
   jfieldID fid;
   u64_t popt;
   char *local_libName;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_libName = (char *) (*env)->GetStringUTFChars(env, libName, NULL);
   rc_CreateL = optCreateL((optHandle_t *)&popt.p, local_libName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, libName, local_libName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, popt.i);
   return rc_CreateL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_Free(JNIEnv *env, jobject obj)
{
   int rc_Free;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_Free = optFree((optHandle_t *)&popt.p);
   (*env)->SetLongField(env, obj, fid, popt.i);
   return rc_Free;
}


static int  OPT_CALLCONV dll_optReadFromCmdArgs_cb(char *argv, int *idx)
{
   return 0;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadDefinition(JNIEnv *env, jobject obj, jstring fn)
{
   int rc_optReadDefinition;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_fn;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_fn = (char *)(*env)->GetStringUTFChars(env, fn, NULL);
   rc_optReadDefinition = optReadDefinition((optHandle_t)popt.p, local_fn);
   (*env)->ReleaseStringUTFChars(env, fn, local_fn);
   return rc_optReadDefinition;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadDefinitionFromPChar(JNIEnv *env, jobject obj, jobjectArray p)
{
   int rc_optReadDefinitionFromPChar;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_p;
   char buffer_p[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_p[0] = '\0';
   rc_optReadDefinitionFromPChar = optReadDefinitionFromPChar((optHandle_t)popt.p, buffer_p);
   local_p = (*env)->NewStringUTF(env, buffer_p);
   (*env)->SetObjectArrayElement(env, p, 0, local_p);
   return rc_optReadDefinitionFromPChar;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadParameterFile(JNIEnv *env, jobject obj, jstring fn)
{
   int rc_optReadParameterFile;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_fn;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_fn = (char *)(*env)->GetStringUTFChars(env, fn, NULL);
   rc_optReadParameterFile = optReadParameterFile((optHandle_t)popt.p, local_fn);
   (*env)->ReleaseStringUTFChars(env, fn, local_fn);
   return rc_optReadParameterFile;
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromStr(JNIEnv *env, jobject obj, jstring s)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_s;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_s = (char *)(*env)->GetStringUTFChars(env, s, NULL);
   optReadFromStr((optHandle_t)popt.p, local_s);
   (*env)->ReleaseStringUTFChars(env, s, local_s);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_WriteParameterFile(JNIEnv *env, jobject obj, jstring fn)
{
   int rc_optWriteParameterFile;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_fn;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_fn = (char *)(*env)->GetStringUTFChars(env, fn, NULL);
   rc_optWriteParameterFile = optWriteParameterFile((optHandle_t)popt.p, local_fn);
   (*env)->ReleaseStringUTFChars(env, fn, local_fn);
   return rc_optWriteParameterFile;
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ClearMessages(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optClearMessages((optHandle_t)popt.p);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_AddMessage(JNIEnv *env, jobject obj, jstring info)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_info;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_info = (char *)(*env)->GetStringUTFChars(env, info, NULL);
   optAddMessage((optHandle_t)popt.p, local_info);
   (*env)->ReleaseStringUTFChars(env, info, local_info);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_GetMessage(JNIEnv *env, jobject obj, jint NrMsg, jobjectArray info, jintArray iType)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_info;
   char buffer_info[256];
   int local_iType[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_info[0] = '\0';
   optGetMessage((optHandle_t)popt.p, NrMsg, buffer_info, local_iType);
   local_info = (*env)->NewStringUTF(env, buffer_info);
   (*env)->SetObjectArrayElement(env, info, 0, local_info);
   (*env)->SetIntArrayRegion(env, iType, 0, 1, local_iType);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ResetAll(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optResetAll((optHandle_t)popt.p);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ResetAllRecent(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optResetAllRecent((optHandle_t)popt.p);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ResetRecentChanges(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optResetRecentChanges((optHandle_t)popt.p);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ShowHelp(JNIEnv *env, jobject obj, jstring AHlpID)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AHlpID;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AHlpID = (char *)(*env)->GetStringUTFChars(env, AHlpID, NULL);
   optShowHelp((optHandle_t)popt.p, local_AHlpID);
   (*env)->ReleaseStringUTFChars(env, AHlpID, local_AHlpID);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_ResetNr(JNIEnv *env, jobject obj, jint ANr)
{
   int rc_optResetNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optResetNr = optResetNr((optHandle_t)popt.p, ANr);
   return rc_optResetNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_FindStr(JNIEnv *env, jobject obj, jstring AName, jintArray ANr, jintArray ARefNr)
{
   int rc_optFindStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   int local_ANr[1];
   int local_ARefNr[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   rc_optFindStr = optFindStr((optHandle_t)popt.p, local_AName, local_ANr, local_ARefNr);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   (*env)->SetIntArrayRegion(env, ANr, 0, 1, local_ANr);
   (*env)->SetIntArrayRegion(env, ARefNr, 0, 1, local_ARefNr);
   return rc_optFindStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetInfoNr(JNIEnv *env, jobject obj, jint ANr, jintArray ADefined, jintArray ADefinedR, jintArray ARefNr, jintArray ADataType, jintArray AOptType, jintArray ASubType)
{
   int rc_optGetInfoNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_ADefined[1];
   int local_ADefinedR[1];
   int local_ARefNr[1];
   int local_ADataType[1];
   int local_AOptType[1];
   int local_ASubType[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetInfoNr = optGetInfoNr((optHandle_t)popt.p, ANr, local_ADefined, local_ADefinedR, local_ARefNr, local_ADataType, local_AOptType, local_ASubType);
   (*env)->SetIntArrayRegion(env, ADefined, 0, 1, local_ADefined);
   (*env)->SetIntArrayRegion(env, ADefinedR, 0, 1, local_ADefinedR);
   (*env)->SetIntArrayRegion(env, ARefNr, 0, 1, local_ARefNr);
   (*env)->SetIntArrayRegion(env, ADataType, 0, 1, local_ADataType);
   (*env)->SetIntArrayRegion(env, AOptType, 0, 1, local_AOptType);
   (*env)->SetIntArrayRegion(env, ASubType, 0, 1, local_ASubType);
   return rc_optGetInfoNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetValuesNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASName, jintArray AIVal, jdoubleArray ADVal, jobjectArray ASVal)
{
   int rc_optGetValuesNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_ASName;
   char buffer_ASName[256];
   int local_AIVal[1];
   double local_ADVal[1];
   jstring local_ASVal;
   char buffer_ASVal[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_ASName[0] = '\0';
   buffer_ASVal[0] = '\0';
   rc_optGetValuesNr = optGetValuesNr((optHandle_t)popt.p, ANr, buffer_ASName, local_AIVal, local_ADVal, buffer_ASVal);
   local_ASName = (*env)->NewStringUTF(env, buffer_ASName);
   (*env)->SetObjectArrayElement(env, ASName, 0, local_ASName);
   (*env)->SetIntArrayRegion(env, AIVal, 0, 1, local_AIVal);
   (*env)->SetDoubleArrayRegion(env, ADVal, 0, 1, local_ADVal);
   local_ASVal = (*env)->NewStringUTF(env, buffer_ASVal);
   (*env)->SetObjectArrayElement(env, ASVal, 0, local_ASVal);
   return rc_optGetValuesNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetValuesNr(JNIEnv *env, jobject obj, jint ANr, jint AIVal, jdouble ADVal, jstring ASVal)
{
   int rc_optSetValuesNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_ASVal;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_ASVal = (char *)(*env)->GetStringUTFChars(env, ASVal, NULL);
   rc_optSetValuesNr = optSetValuesNr((optHandle_t)popt.p, ANr, AIVal, ADVal, local_ASVal);
   (*env)->ReleaseStringUTFChars(env, ASVal, local_ASVal);
   return rc_optSetValuesNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetValues2Nr(JNIEnv *env, jobject obj, jint ANr, jint AIVal, jdouble ADVal, jstring ASVal)
{
   int rc_optSetValues2Nr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_ASVal;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_ASVal = (char *)(*env)->GetStringUTFChars(env, ASVal, NULL);
   rc_optSetValues2Nr = optSetValues2Nr((optHandle_t)popt.p, ANr, AIVal, ADVal, local_ASVal);
   (*env)->ReleaseStringUTFChars(env, ASVal, local_ASVal);
   return rc_optSetValues2Nr;
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_Version(JNIEnv *env, jobject obj, jobjectArray sversion)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_sversion;
   char buffer_sversion[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_sversion[0] = '\0';
   optVersion((optHandle_t)popt.p, buffer_sversion);
   local_sversion = (*env)->NewStringUTF(env, buffer_sversion);
   (*env)->SetObjectArrayElement(env, sversion, 0, local_sversion);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_DefinitionFile(JNIEnv *env, jobject obj, jobjectArray sfilename)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_sfilename;
   char buffer_sfilename[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_sfilename[0] = '\0';
   optDefinitionFile((optHandle_t)popt.p, buffer_sfilename);
   local_sfilename = (*env)->NewStringUTF(env, buffer_sfilename);
   (*env)->SetObjectArrayElement(env, sfilename, 0, local_sfilename);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetFromAnyStrList(JNIEnv *env, jobject obj, jint idash, jobjectArray skey, jobjectArray sval)
{
   int rc_optGetFromAnyStrList;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_skey;
   char buffer_skey[256];
   jstring local_sval;
   char buffer_sval[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_skey[0] = '\0';
   buffer_sval[0] = '\0';
   rc_optGetFromAnyStrList = optGetFromAnyStrList((optHandle_t)popt.p, idash, buffer_skey, buffer_sval);
   local_skey = (*env)->NewStringUTF(env, buffer_skey);
   (*env)->SetObjectArrayElement(env, skey, 0, local_skey);
   local_sval = (*env)->NewStringUTF(env, buffer_sval);
   (*env)->SetObjectArrayElement(env, sval, 0, local_sval);
   return rc_optGetFromAnyStrList;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetFromListStr(JNIEnv *env, jobject obj, jstring skey, jobjectArray sval)
{
   int rc_optGetFromListStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_skey;
   jstring local_sval;
   char buffer_sval[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_skey = (char *)(*env)->GetStringUTFChars(env, skey, NULL);
   buffer_sval[0] = '\0';
   rc_optGetFromListStr = optGetFromListStr((optHandle_t)popt.p, local_skey, buffer_sval);
   (*env)->ReleaseStringUTFChars(env, skey, local_skey);
   local_sval = (*env)->NewStringUTF(env, buffer_sval);
   (*env)->SetObjectArrayElement(env, sval, 0, local_sval);
   return rc_optGetFromListStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_ListCountStr(JNIEnv *env, jobject obj, jstring skey)
{
   int rc_optListCountStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_skey;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_skey = (char *)(*env)->GetStringUTFChars(env, skey, NULL);
   rc_optListCountStr = optListCountStr((optHandle_t)popt.p, local_skey);
   (*env)->ReleaseStringUTFChars(env, skey, local_skey);
   return rc_optListCountStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_ReadFromListStr(JNIEnv *env, jobject obj, jstring skey, jint iPos, jobjectArray sval)
{
   int rc_optReadFromListStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_skey;
   jstring local_sval;
   char buffer_sval[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_skey = (char *)(*env)->GetStringUTFChars(env, skey, NULL);
   buffer_sval[0] = '\0';
   rc_optReadFromListStr = optReadFromListStr((optHandle_t)popt.p, local_skey, iPos, buffer_sval);
   (*env)->ReleaseStringUTFChars(env, skey, local_skey);
   local_sval = (*env)->NewStringUTF(env, buffer_sval);
   (*env)->SetObjectArrayElement(env, sval, 0, local_sval);
   return rc_optReadFromListStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SynonymCount(JNIEnv *env, jobject obj)
{
   int rc_optSynonymCount;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optSynonymCount = optSynonymCount((optHandle_t)popt.p);
   return rc_optSynonymCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetSynonym(JNIEnv *env, jobject obj, jint NrSyn, jobjectArray SSyn, jobjectArray SName)
{
   int rc_optGetSynonym;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_SSyn;
   char buffer_SSyn[256];
   jstring local_SName;
   char buffer_SName[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_SSyn[0] = '\0';
   buffer_SName[0] = '\0';
   rc_optGetSynonym = optGetSynonym((optHandle_t)popt.p, NrSyn, buffer_SSyn, buffer_SName);
   local_SSyn = (*env)->NewStringUTF(env, buffer_SSyn);
   (*env)->SetObjectArrayElement(env, SSyn, 0, local_SSyn);
   local_SName = (*env)->NewStringUTF(env, buffer_SName);
   (*env)->SetObjectArrayElement(env, SName, 0, local_SName);
   return rc_optGetSynonym;
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_EchoSet(JNIEnv *env, jobject obj, jint AIVal)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optEchoSet((optHandle_t)popt.p, AIVal);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_EOLOnlySet(JNIEnv *env, jobject obj, jint AIVal)
{
   int rc_optEOLOnlySet;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optEOLOnlySet = optEOLOnlySet((optHandle_t)popt.p, AIVal);
   return rc_optEOLOnlySet;
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_NoBoundsSet(JNIEnv *env, jobject obj, jint AIVal)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optNoBoundsSet((optHandle_t)popt.p, AIVal);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_EOLChars(JNIEnv *env, jobject obj, jobjectArray EOLChars)
{
   int rc_optEOLChars;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_EOLChars;
   char buffer_EOLChars[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_EOLChars[0] = '\0';
   rc_optEOLChars = optEOLChars((optHandle_t)popt.p, buffer_EOLChars);
   local_EOLChars = (*env)->NewStringUTF(env, buffer_EOLChars);
   (*env)->SetObjectArrayElement(env, EOLChars, 0, local_EOLChars);
   return rc_optEOLChars;
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ErrorCount(JNIEnv *env, jobject obj, jintArray iErrors, jintArray iWarnings)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_iErrors[1];
   int local_iWarnings[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optErrorCount((optHandle_t)popt.p, local_iErrors, local_iWarnings);
   (*env)->SetIntArrayRegion(env, iErrors, 0, 1, local_iErrors);
   (*env)->SetIntArrayRegion(env, iWarnings, 0, 1, local_iWarnings);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetBoundsInt(JNIEnv *env, jobject obj, jint ANr, jintArray ilval, jintArray ihval, jintArray idval)
{
   int rc_optGetBoundsInt;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_ilval[1];
   int local_ihval[1];
   int local_idval[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetBoundsInt = optGetBoundsInt((optHandle_t)popt.p, ANr, local_ilval, local_ihval, local_idval);
   (*env)->SetIntArrayRegion(env, ilval, 0, 1, local_ilval);
   (*env)->SetIntArrayRegion(env, ihval, 0, 1, local_ihval);
   (*env)->SetIntArrayRegion(env, idval, 0, 1, local_idval);
   return rc_optGetBoundsInt;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetBoundsDbl(JNIEnv *env, jobject obj, jint ANr, jdoubleArray dlval, jdoubleArray dhval, jdoubleArray ddval)
{
   int rc_optGetBoundsDbl;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   double local_dlval[1];
   double local_dhval[1];
   double local_ddval[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetBoundsDbl = optGetBoundsDbl((optHandle_t)popt.p, ANr, local_dlval, local_dhval, local_ddval);
   (*env)->SetDoubleArrayRegion(env, dlval, 0, 1, local_dlval);
   (*env)->SetDoubleArrayRegion(env, dhval, 0, 1, local_dhval);
   (*env)->SetDoubleArrayRegion(env, ddval, 0, 1, local_ddval);
   return rc_optGetBoundsDbl;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDefaultStr(JNIEnv *env, jobject obj, jint ANr, jobjectArray sval)
{
   int rc_optGetDefaultStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_sval;
   char buffer_sval[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_sval[0] = '\0';
   rc_optGetDefaultStr = optGetDefaultStr((optHandle_t)popt.p, ANr, buffer_sval);
   local_sval = (*env)->NewStringUTF(env, buffer_sval);
   (*env)->SetObjectArrayElement(env, sval, 0, local_sval);
   return rc_optGetDefaultStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetIntNr(JNIEnv *env, jobject obj, jint ANr, jintArray AIVal)
{
   int rc_optGetIntNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_AIVal[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetIntNr = optGetIntNr((optHandle_t)popt.p, ANr, local_AIVal);
   (*env)->SetIntArrayRegion(env, AIVal, 0, 1, local_AIVal);
   return rc_optGetIntNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetInt2Nr(JNIEnv *env, jobject obj, jint ANr, jintArray AIVal)
{
   int rc_optGetInt2Nr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_AIVal[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetInt2Nr = optGetInt2Nr((optHandle_t)popt.p, ANr, local_AIVal);
   (*env)->SetIntArrayRegion(env, AIVal, 0, 1, local_AIVal);
   return rc_optGetInt2Nr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetIntNr(JNIEnv *env, jobject obj, jint ANr, jint AIVal)
{
   int rc_optSetIntNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optSetIntNr = optSetIntNr((optHandle_t)popt.p, ANr, AIVal);
   return rc_optSetIntNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetInt2Nr(JNIEnv *env, jobject obj, jint ANr, jint AIVal)
{
   int rc_optSetInt2Nr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optSetInt2Nr = optSetInt2Nr((optHandle_t)popt.p, ANr, AIVal);
   return rc_optSetInt2Nr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetStrNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASVal)
{
   int rc_optGetStrNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_ASVal;
   char buffer_ASVal[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_ASVal[0] = '\0';
   rc_optGetStrNr = optGetStrNr((optHandle_t)popt.p, ANr, buffer_ASVal);
   local_ASVal = (*env)->NewStringUTF(env, buffer_ASVal);
   (*env)->SetObjectArrayElement(env, ASVal, 0, local_ASVal);
   return rc_optGetStrNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetOptHelpNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray AName, jintArray AHc, jintArray AGroup)
{
   int rc_optGetOptHelpNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AName;
   char buffer_AName[256];
   int local_AHc[1];
   int local_AGroup[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AName[0] = '\0';
   rc_optGetOptHelpNr = optGetOptHelpNr((optHandle_t)popt.p, ANr, buffer_AName, local_AHc, local_AGroup);
   local_AName = (*env)->NewStringUTF(env, buffer_AName);
   (*env)->SetObjectArrayElement(env, AName, 0, local_AName);
   (*env)->SetIntArrayRegion(env, AHc, 0, 1, local_AHc);
   (*env)->SetIntArrayRegion(env, AGroup, 0, 1, local_AGroup);
   return rc_optGetOptHelpNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumHelp(JNIEnv *env, jobject obj, jint ANr, jint AOrd, jintArray AHc, jobjectArray AHelpStr)
{
   int rc_optGetEnumHelp;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_AHc[1];
   jstring local_AHelpStr;
   char buffer_AHelpStr[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AHelpStr[0] = '\0';
   rc_optGetEnumHelp = optGetEnumHelp((optHandle_t)popt.p, ANr, AOrd, local_AHc, buffer_AHelpStr);
   (*env)->SetIntArrayRegion(env, AHc, 0, 1, local_AHc);
   local_AHelpStr = (*env)->NewStringUTF(env, buffer_AHelpStr);
   (*env)->SetObjectArrayElement(env, AHelpStr, 0, local_AHelpStr);
   return rc_optGetEnumHelp;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumStrNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASVal, jintArray AOrd)
{
   int rc_optGetEnumStrNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_ASVal;
   char buffer_ASVal[256];
   int local_AOrd[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_ASVal[0] = '\0';
   rc_optGetEnumStrNr = optGetEnumStrNr((optHandle_t)popt.p, ANr, buffer_ASVal, local_AOrd);
   local_ASVal = (*env)->NewStringUTF(env, buffer_ASVal);
   (*env)->SetObjectArrayElement(env, ASVal, 0, local_ASVal);
   (*env)->SetIntArrayRegion(env, AOrd, 0, 1, local_AOrd);
   return rc_optGetEnumStrNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumCount(JNIEnv *env, jobject obj, jint ANr, jintArray ACount)
{
   int rc_optGetEnumCount;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_ACount[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetEnumCount = optGetEnumCount((optHandle_t)popt.p, ANr, local_ACount);
   (*env)->SetIntArrayRegion(env, ACount, 0, 1, local_ACount);
   return rc_optGetEnumCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEnumValue(JNIEnv *env, jobject obj, jint ANr, jint AOrd, jintArray AValInt, jobjectArray AValStr)
{
   int rc_optGetEnumValue;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_AValInt[1];
   jstring local_AValStr;
   char buffer_AValStr[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AValStr[0] = '\0';
   rc_optGetEnumValue = optGetEnumValue((optHandle_t)popt.p, ANr, AOrd, local_AValInt, buffer_AValStr);
   (*env)->SetIntArrayRegion(env, AValInt, 0, 1, local_AValInt);
   local_AValStr = (*env)->NewStringUTF(env, buffer_AValStr);
   (*env)->SetObjectArrayElement(env, AValStr, 0, local_AValStr);
   return rc_optGetEnumValue;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetStr2Nr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASVal)
{
   int rc_optGetStr2Nr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_ASVal;
   char buffer_ASVal[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_ASVal[0] = '\0';
   rc_optGetStr2Nr = optGetStr2Nr((optHandle_t)popt.p, ANr, buffer_ASVal);
   local_ASVal = (*env)->NewStringUTF(env, buffer_ASVal);
   (*env)->SetObjectArrayElement(env, ASVal, 0, local_ASVal);
   return rc_optGetStr2Nr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetStrNr(JNIEnv *env, jobject obj, jint ANr, jstring ASVal)
{
   int rc_optSetStrNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_ASVal;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_ASVal = (char *)(*env)->GetStringUTFChars(env, ASVal, NULL);
   rc_optSetStrNr = optSetStrNr((optHandle_t)popt.p, ANr, local_ASVal);
   (*env)->ReleaseStringUTFChars(env, ASVal, local_ASVal);
   return rc_optSetStrNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetStr2Nr(JNIEnv *env, jobject obj, jint ANr, jstring ASVal)
{
   int rc_optSetStr2Nr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_ASVal;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_ASVal = (char *)(*env)->GetStringUTFChars(env, ASVal, NULL);
   rc_optSetStr2Nr = optSetStr2Nr((optHandle_t)popt.p, ANr, local_ASVal);
   (*env)->ReleaseStringUTFChars(env, ASVal, local_ASVal);
   return rc_optSetStr2Nr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDblNr(JNIEnv *env, jobject obj, jint ANr, jdoubleArray ADVal)
{
   int rc_optGetDblNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   double local_ADVal[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetDblNr = optGetDblNr((optHandle_t)popt.p, ANr, local_ADVal);
   (*env)->SetDoubleArrayRegion(env, ADVal, 0, 1, local_ADVal);
   return rc_optGetDblNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDbl2Nr(JNIEnv *env, jobject obj, jint ANr, jdoubleArray ADVal)
{
   int rc_optGetDbl2Nr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   double local_ADVal[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetDbl2Nr = optGetDbl2Nr((optHandle_t)popt.p, ANr, local_ADVal);
   (*env)->SetDoubleArrayRegion(env, ADVal, 0, 1, local_ADVal);
   return rc_optGetDbl2Nr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetDblNr(JNIEnv *env, jobject obj, jint ANr, jdouble ADVal)
{
   int rc_optSetDblNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optSetDblNr = optSetDblNr((optHandle_t)popt.p, ANr, ADVal);
   return rc_optSetDblNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetDbl2Nr(JNIEnv *env, jobject obj, jint ANr, jdouble ADVal)
{
   int rc_optSetDbl2Nr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optSetDbl2Nr = optSetDbl2Nr((optHandle_t)popt.p, ANr, ADVal);
   return rc_optSetDbl2Nr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetValStr(JNIEnv *env, jobject obj, jstring AName, jobjectArray ASVal)
{
   int rc_optGetValStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   jstring local_ASVal;
   char buffer_ASVal[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   buffer_ASVal[0] = '\0';
   rc_optGetValStr = optGetValStr((optHandle_t)popt.p, local_AName, buffer_ASVal);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   local_ASVal = (*env)->NewStringUTF(env, buffer_ASVal);
   (*env)->SetObjectArrayElement(env, ASVal, 0, local_ASVal);
   return rc_optGetValStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVal2Str(JNIEnv *env, jobject obj, jstring AName, jobjectArray ASVal)
{
   int rc_optGetVal2Str;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   jstring local_ASVal;
   char buffer_ASVal[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   buffer_ASVal[0] = '\0';
   rc_optGetVal2Str = optGetVal2Str((optHandle_t)popt.p, local_AName, buffer_ASVal);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   local_ASVal = (*env)->NewStringUTF(env, buffer_ASVal);
   (*env)->SetObjectArrayElement(env, ASVal, 0, local_ASVal);
   return rc_optGetVal2Str;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetNameNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASName)
{
   int rc_optGetNameNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_ASName;
   char buffer_ASName[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_ASName[0] = '\0';
   rc_optGetNameNr = optGetNameNr((optHandle_t)popt.p, ANr, buffer_ASName);
   local_ASName = (*env)->NewStringUTF(env, buffer_ASName);
   (*env)->SetObjectArrayElement(env, ASName, 0, local_ASName);
   return rc_optGetNameNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDefinedNr(JNIEnv *env, jobject obj, jint ANr, jintArray AIVal)
{
   int rc_optGetDefinedNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_AIVal[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetDefinedNr = optGetDefinedNr((optHandle_t)popt.p, ANr, local_AIVal);
   (*env)->SetIntArrayRegion(env, AIVal, 0, 1, local_AIVal);
   return rc_optGetDefinedNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetHelpNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray ASOpt, jobjectArray ASHelp)
{
   int rc_optGetHelpNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_ASOpt;
   char buffer_ASOpt[256];
   jstring local_ASHelp;
   char buffer_ASHelp[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_ASOpt[0] = '\0';
   buffer_ASHelp[0] = '\0';
   rc_optGetHelpNr = optGetHelpNr((optHandle_t)popt.p, ANr, buffer_ASOpt, buffer_ASHelp);
   local_ASOpt = (*env)->NewStringUTF(env, buffer_ASOpt);
   (*env)->SetObjectArrayElement(env, ASOpt, 0, local_ASOpt);
   local_ASHelp = (*env)->NewStringUTF(env, buffer_ASHelp);
   (*env)->SetObjectArrayElement(env, ASHelp, 0, local_ASHelp);
   return rc_optGetHelpNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetGroupNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray AName, jintArray AGroup, jintArray AHc, jobjectArray AHelp)
{
   int rc_optGetGroupNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AName;
   char buffer_AName[256];
   int local_AGroup[1];
   int local_AHc[1];
   jstring local_AHelp;
   char buffer_AHelp[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AName[0] = '\0';
   buffer_AHelp[0] = '\0';
   rc_optGetGroupNr = optGetGroupNr((optHandle_t)popt.p, ANr, buffer_AName, local_AGroup, local_AHc, buffer_AHelp);
   local_AName = (*env)->NewStringUTF(env, buffer_AName);
   (*env)->SetObjectArrayElement(env, AName, 0, local_AName);
   (*env)->SetIntArrayRegion(env, AGroup, 0, 1, local_AGroup);
   (*env)->SetIntArrayRegion(env, AHc, 0, 1, local_AHc);
   local_AHelp = (*env)->NewStringUTF(env, buffer_AHelp);
   (*env)->SetObjectArrayElement(env, AHelp, 0, local_AHelp);
   return rc_optGetGroupNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetGroupGrpNr(JNIEnv *env, jobject obj, jint AGroup)
{
   int rc_optGetGroupGrpNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetGroupGrpNr = optGetGroupGrpNr((optHandle_t)popt.p, AGroup);
   return rc_optGetGroupGrpNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetOptGroupNr(JNIEnv *env, jobject obj, jint ANr)
{
   int rc_optGetOptGroupNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optGetOptGroupNr = optGetOptGroupNr((optHandle_t)popt.p, ANr);
   return rc_optGetOptGroupNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDotOptNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray VEName, jintArray AObjNr, jintArray ADim, jdoubleArray AValue)
{
   int rc_optGetDotOptNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_VEName;
   char buffer_VEName[256];
   int local_AObjNr[1];
   int local_ADim[1];
   double local_AValue[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_VEName[0] = '\0';
   rc_optGetDotOptNr = optGetDotOptNr((optHandle_t)popt.p, ANr, buffer_VEName, local_AObjNr, local_ADim, local_AValue);
   local_VEName = (*env)->NewStringUTF(env, buffer_VEName);
   (*env)->SetObjectArrayElement(env, VEName, 0, local_VEName);
   (*env)->SetIntArrayRegion(env, AObjNr, 0, 1, local_AObjNr);
   (*env)->SetIntArrayRegion(env, ADim, 0, 1, local_ADim);
   (*env)->SetDoubleArrayRegion(env, AValue, 0, 1, local_AValue);
   return rc_optGetDotOptNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetDotOptUel(JNIEnv *env, jobject obj, jint ANr, jint ADim, jobjectArray AUEL)
{
   int rc_optGetDotOptUel;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AUEL;
   char buffer_AUEL[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AUEL[0] = '\0';
   rc_optGetDotOptUel = optGetDotOptUel((optHandle_t)popt.p, ANr, ADim, buffer_AUEL);
   local_AUEL = (*env)->NewStringUTF(env, buffer_AUEL);
   (*env)->SetObjectArrayElement(env, AUEL, 0, local_AUEL);
   return rc_optGetDotOptUel;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVarEquMapNr(JNIEnv *env, jobject obj, jint maptype, jint ANr, jobjectArray EquName, jobjectArray VarName, jintArray EquDim, jintArray VarDim, jintArray AValue)
{
   int rc_optGetVarEquMapNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_EquName;
   char buffer_EquName[256];
   jstring local_VarName;
   char buffer_VarName[256];
   int local_EquDim[1];
   int local_VarDim[1];
   int local_AValue[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_EquName[0] = '\0';
   buffer_VarName[0] = '\0';
   rc_optGetVarEquMapNr = optGetVarEquMapNr((optHandle_t)popt.p, maptype, ANr, buffer_EquName, buffer_VarName, local_EquDim, local_VarDim, local_AValue);
   local_EquName = (*env)->NewStringUTF(env, buffer_EquName);
   (*env)->SetObjectArrayElement(env, EquName, 0, local_EquName);
   local_VarName = (*env)->NewStringUTF(env, buffer_VarName);
   (*env)->SetObjectArrayElement(env, VarName, 0, local_VarName);
   (*env)->SetIntArrayRegion(env, EquDim, 0, 1, local_EquDim);
   (*env)->SetIntArrayRegion(env, VarDim, 0, 1, local_VarDim);
   (*env)->SetIntArrayRegion(env, AValue, 0, 1, local_AValue);
   return rc_optGetVarEquMapNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEquVarEquMapNr(JNIEnv *env, jobject obj, jint maptype, jint ANr, jint ADim, jobjectArray AIndex)
{
   int rc_optGetEquVarEquMapNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AIndex;
   char buffer_AIndex[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AIndex[0] = '\0';
   rc_optGetEquVarEquMapNr = optGetEquVarEquMapNr((optHandle_t)popt.p, maptype, ANr, ADim, buffer_AIndex);
   local_AIndex = (*env)->NewStringUTF(env, buffer_AIndex);
   (*env)->SetObjectArrayElement(env, AIndex, 0, local_AIndex);
   return rc_optGetEquVarEquMapNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVarVarEquMapNr(JNIEnv *env, jobject obj, jint maptype, jint ANr, jint ADim, jobjectArray AIndex)
{
   int rc_optGetVarVarEquMapNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AIndex;
   char buffer_AIndex[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AIndex[0] = '\0';
   rc_optGetVarVarEquMapNr = optGetVarVarEquMapNr((optHandle_t)popt.p, maptype, ANr, ADim, buffer_AIndex);
   local_AIndex = (*env)->NewStringUTF(env, buffer_AIndex);
   (*env)->SetObjectArrayElement(env, AIndex, 0, local_AIndex);
   return rc_optGetVarVarEquMapNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_VarEquMapCount(JNIEnv *env, jobject obj, jint maptype, jintArray ANrErrors)
{
   int rc_optVarEquMapCount;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_ANrErrors[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optVarEquMapCount = optVarEquMapCount((optHandle_t)popt.p, maptype, local_ANrErrors);
   (*env)->SetIntArrayRegion(env, ANrErrors, 0, 1, local_ANrErrors);
   return rc_optVarEquMapCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetIndicatorNr(JNIEnv *env, jobject obj, jint ANr, jobjectArray EquName, jobjectArray VarName, jintArray EquDim, jintArray VarDim, jintArray AValue)
{
   int rc_optGetIndicatorNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_EquName;
   char buffer_EquName[256];
   jstring local_VarName;
   char buffer_VarName[256];
   int local_EquDim[1];
   int local_VarDim[1];
   int local_AValue[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_EquName[0] = '\0';
   buffer_VarName[0] = '\0';
   rc_optGetIndicatorNr = optGetIndicatorNr((optHandle_t)popt.p, ANr, buffer_EquName, buffer_VarName, local_EquDim, local_VarDim, local_AValue);
   local_EquName = (*env)->NewStringUTF(env, buffer_EquName);
   (*env)->SetObjectArrayElement(env, EquName, 0, local_EquName);
   local_VarName = (*env)->NewStringUTF(env, buffer_VarName);
   (*env)->SetObjectArrayElement(env, VarName, 0, local_VarName);
   (*env)->SetIntArrayRegion(env, EquDim, 0, 1, local_EquDim);
   (*env)->SetIntArrayRegion(env, VarDim, 0, 1, local_VarDim);
   (*env)->SetIntArrayRegion(env, AValue, 0, 1, local_AValue);
   return rc_optGetIndicatorNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetEquIndicatorNr(JNIEnv *env, jobject obj, jint ANr, jint ADim, jobjectArray AIndex)
{
   int rc_optGetEquIndicatorNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AIndex;
   char buffer_AIndex[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AIndex[0] = '\0';
   rc_optGetEquIndicatorNr = optGetEquIndicatorNr((optHandle_t)popt.p, ANr, ADim, buffer_AIndex);
   local_AIndex = (*env)->NewStringUTF(env, buffer_AIndex);
   (*env)->SetObjectArrayElement(env, AIndex, 0, local_AIndex);
   return rc_optGetEquIndicatorNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetVarIndicatorNr(JNIEnv *env, jobject obj, jint ANr, jint ADim, jobjectArray AIndex)
{
   int rc_optGetVarIndicatorNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_AIndex;
   char buffer_AIndex[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_AIndex[0] = '\0';
   rc_optGetVarIndicatorNr = optGetVarIndicatorNr((optHandle_t)popt.p, ANr, ADim, buffer_AIndex);
   local_AIndex = (*env)->NewStringUTF(env, buffer_AIndex);
   (*env)->SetObjectArrayElement(env, AIndex, 0, local_AIndex);
   return rc_optGetVarIndicatorNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_IndicatorCount(JNIEnv *env, jobject obj, jintArray ANrErrors)
{
   int rc_optIndicatorCount;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_ANrErrors[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optIndicatorCount = optIndicatorCount((optHandle_t)popt.p, local_ANrErrors);
   (*env)->SetIntArrayRegion(env, ANrErrors, 0, 1, local_ANrErrors);
   return rc_optIndicatorCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_DotOptCount(JNIEnv *env, jobject obj, jintArray ANrErrors)
{
   int rc_optDotOptCount;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_ANrErrors[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optDotOptCount = optDotOptCount((optHandle_t)popt.p, local_ANrErrors);
   (*env)->SetIntArrayRegion(env, ANrErrors, 0, 1, local_ANrErrors);
   return rc_optDotOptCount;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetRefNr(JNIEnv *env, jobject obj, jint ANr, jint ARefNr)
{
   int rc_optSetRefNr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   rc_optSetRefNr = optSetRefNr((optHandle_t)popt.p, ANr, ARefNr);
   return rc_optSetRefNr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_SetRefNrStr(JNIEnv *env, jobject obj, jstring AOpt, jint ARefNr)
{
   int rc_optSetRefNrStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AOpt;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AOpt = (char *)(*env)->GetStringUTFChars(env, AOpt, NULL);
   rc_optSetRefNrStr = optSetRefNrStr((optHandle_t)popt.p, local_AOpt, ARefNr);
   (*env)->ReleaseStringUTFChars(env, AOpt, local_AOpt);
   return rc_optSetRefNrStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetConstName(JNIEnv *env, jobject obj, jint cgroup, jint cindex, jobjectArray cname)
{
   int rc_optGetConstName;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_cname;
   char buffer_cname[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_cname[0] = '\0';
   rc_optGetConstName = optGetConstName((optHandle_t)popt.p, cgroup, cindex, buffer_cname);
   local_cname = (*env)->NewStringUTF(env, buffer_cname);
   (*env)->SetObjectArrayElement(env, cname, 0, local_cname);
   return rc_optGetConstName;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetTypeName(JNIEnv *env, jobject obj, jint TNr, jobjectArray sTName)
{
   int rc_optGetTypeName;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_sTName;
   char buffer_sTName[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_sTName[0] = '\0';
   rc_optGetTypeName = optGetTypeName((optHandle_t)popt.p, TNr, buffer_sTName);
   local_sTName = (*env)->NewStringUTF(env, buffer_sTName);
   (*env)->SetObjectArrayElement(env, sTName, 0, local_sTName);
   return rc_optGetTypeName;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_LookUp(JNIEnv *env, jobject obj, jstring AOpt)
{
   int rc_optLookUp;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AOpt;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AOpt = (char *)(*env)->GetStringUTFChars(env, AOpt, NULL);
   rc_optLookUp = optLookUp((optHandle_t)popt.p, local_AOpt);
   (*env)->ReleaseStringUTFChars(env, AOpt, local_AOpt);
   return rc_optLookUp;
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromPChar(JNIEnv *env, jobject obj, jobjectArray p)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_p;
   char buffer_p[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_p[0] = '\0';
   optReadFromPChar((optHandle_t)popt.p, buffer_p);
   local_p = (*env)->NewStringUTF(env, buffer_p);
   (*env)->SetObjectArrayElement(env, p, 0, local_p);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromCmdLine(JNIEnv *env, jobject obj, jobjectArray p)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_p;
   char buffer_p[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_p[0] = '\0';
   optReadFromCmdLine((optHandle_t)popt.p, buffer_p);
   local_p = (*env)->NewStringUTF(env, buffer_p);
   (*env)->SetObjectArrayElement(env, p, 0, local_p);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_ReadFromCmdArgs(JNIEnv *env, jobject obj, jstring cb)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_cb;
   int   have_cb = 0;
   TArgvCB_t ptr_cb = NULL;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   if(cb != NULL)
   {
     local_cb = (char *)(*env)->GetStringUTFChars(env, cb, NULL);
     if(strcmp(local_cb,""))
       have_cb=1;
   }
   if(have_cb)
   {
     local_cb = (char *)(*env)->GetStringUTFChars(env, cb, NULL);
     methodname_optReadFromCmdArgs_cb = getMethodName_(local_cb);
     if(methodname_optReadFromCmdArgs_cb == NULL) printerr("Method name incomplete", local_cb);
     classname_optReadFromCmdArgs_cb = getClassName_(local_cb);
     if(classname_optReadFromCmdArgs_cb == NULL) printerr("Class name incomplete", local_cb);
     sig_optReadFromCmdArgs_cb = "([Ljava/lang/String;[I)I";
     ptr_cb=dll_optReadFromCmdArgs_cb;
   }
   optReadFromCmdArgs((optHandle_t)popt.p, ptr_cb);
   if(cb != NULL)
      (*env)->ReleaseStringUTFChars(env, cb, local_cb);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetNameOpt(JNIEnv *env, jobject obj, jstring ASVal, jobjectArray solver, jintArray opt)
{
   int rc_optGetNameOpt;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_ASVal;
   jstring local_solver;
   char buffer_solver[256];
   int local_opt[1];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_ASVal = (char *)(*env)->GetStringUTFChars(env, ASVal, NULL);
   buffer_solver[0] = '\0';
   rc_optGetNameOpt = optGetNameOpt((optHandle_t)popt.p, local_ASVal, buffer_solver, local_opt);
   (*env)->ReleaseStringUTFChars(env, ASVal, local_ASVal);
   local_solver = (*env)->NewStringUTF(env, buffer_solver);
   (*env)->SetObjectArrayElement(env, solver, 0, local_solver);
   (*env)->SetIntArrayRegion(env, opt, 0, 1, local_opt);
   return rc_optGetNameOpt;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_opt_ResetStr(JNIEnv *env, jobject obj, jstring AName)
{
   int rc_optResetStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   rc_optResetStr = optResetStr((optHandle_t)popt.p, local_AName);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   return rc_optResetStr;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_opt_GetDefinedStr(JNIEnv *env, jobject obj, jstring AName)
{
   int rc_optGetDefinedStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   rc_optGetDefinedStr = optGetDefinedStr((optHandle_t)popt.p, local_AName);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   return rc_optGetDefinedStr;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GetIntStr(JNIEnv *env, jobject obj, jstring AName)
{
   int rc_optGetIntStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   rc_optGetIntStr = optGetIntStr((optHandle_t)popt.p, local_AName);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   return rc_optGetIntStr;
}

JNIEXPORT jdouble JNICALL Java_com_gams_api_opt_GetDblStr(JNIEnv *env, jobject obj, jstring AName)
{
   double rc_optGetDblStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0.0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   rc_optGetDblStr = optGetDblStr((optHandle_t)popt.p, local_AName);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   return rc_optGetDblStr;
}

JNIEXPORT jstring JNICALL Java_com_gams_api_opt_GetStrStr(JNIEnv *env, jobject obj, jstring AName, jobjectArray sst_result)
{
   char *rc_optGetStrStr;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_sst;
   char buffer_sst[256];
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return NULL;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   buffer_sst[0] = '\0';
   rc_optGetStrStr = optGetStrStr((optHandle_t)popt.p, local_AName, buffer_sst);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   local_sst = (*env)->NewStringUTF(env, buffer_sst);
   (*env)->SetObjectArrayElement(env, sst_result, 0, local_sst);
   return (*env)->NewStringUTF(env, rc_optGetStrStr);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_SetIntStr(JNIEnv *env, jobject obj, jstring AName, jint AIVal)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   optSetIntStr((optHandle_t)popt.p, local_AName, AIVal);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_SetDblStr(JNIEnv *env, jobject obj, jstring AName, jdouble ADVal)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   optSetDblStr((optHandle_t)popt.p, local_AName, ADVal);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_SetStrStr(JNIEnv *env, jobject obj, jstring AName, jstring ASVal)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   char *local_ASVal;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return ;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   local_ASVal = (char *)(*env)->GetStringUTFChars(env, ASVal, NULL);
   optSetStrStr((optHandle_t)popt.p, local_AName, local_ASVal);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   (*env)->ReleaseStringUTFChars(env, ASVal, local_ASVal);
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_opt_IsDeprecated(JNIEnv *env, jobject obj, jstring AName)
{
   int rc_optIsDeprecated;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_AName;
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   local_AName = (char *)(*env)->GetStringUTFChars(env, AName, NULL);
   rc_optIsDeprecated = optIsDeprecated((optHandle_t)popt.p, local_AName);
   (*env)->ReleaseStringUTFChars(env, AName, local_AName);
   return rc_optIsDeprecated;
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_Count(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   return optCount((optHandle_t)popt.p);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_MessageCount(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   return optMessageCount((optHandle_t)popt.p);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_GroupCount(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   return optGroupCount((optHandle_t)popt.p);
}

JNIEXPORT jint JNICALL Java_com_gams_api_opt_RecentEnabled(JNIEnv *env, jobject obj)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return 0;
   popt.i = (*env)->GetLongField(env, obj, fid);
   return optRecentEnabled((optHandle_t)popt.p);
}

JNIEXPORT void JNICALL Java_com_gams_api_opt_RecentEnabledSet(JNIEnv *env, jobject obj, jint x)
{
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return;
   popt.i = (*env)->GetLongField(env, obj, fid);
   optRecentEnabledSet((optHandle_t)popt.p, x);
}

JNIEXPORT jstring JNICALL Java_com_gams_api_opt_Separator(JNIEnv *env, jobject obj, jobjectArray sst_result)
{
   char *rc_optSeparator;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_sst;
   char buffer_sst[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return NULL;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_sst[0] = '\0';
   rc_optSeparator = optSeparator((optHandle_t)popt.p, buffer_sst);
   local_sst = (*env)->NewStringUTF(env, buffer_sst);
   (*env)->SetObjectArrayElement(env, sst_result, 0, local_sst);
   return  (*env)->NewStringUTF(env, rc_optSeparator);
}

JNIEXPORT jstring JNICALL Java_com_gams_api_opt_StringQuote(JNIEnv *env, jobject obj, jobjectArray sst_result)
{
   char *rc_optStringQuote;
   jfieldID fid;
   u64_t popt;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_sst;
   char buffer_sst[256];
   fid = (*env)->GetFieldID(env, cls, "optPtr", "J");
   if (fid == NULL) return NULL;
   popt.i = (*env)->GetLongField(env, obj, fid);
   buffer_sst[0] = '\0';
   rc_optStringQuote = optStringQuote((optHandle_t)popt.p, buffer_sst);
   local_sst = (*env)->NewStringUTF(env, buffer_sst);
   (*env)->SetObjectArrayElement(env, sst_result, 0, local_sst);
   return  (*env)->NewStringUTF(env, rc_optStringQuote);
}
